import Ripple.PopulationProtocol.Majority.SSEM.UpperBound.Time.DrainNoWakeBound
import Ripple.PopulationProtocol.Majority.SSEM.UpperBound.Time.DrainNoWakeCert

namespace SSEM

open scoped BigOperators ENNReal

variable {Q X Y : Type*} {n : ℕ}

/-- Two deterministic executions agree up to time `t` if the two schedulers agree
on all scheduler coordinates `< t`. -/
theorem execution_eq_of_scheduler_agree
    {P : Protocol Q X Y} {C₀ : Config Q X n}
    {γ δ : DetScheduler n} :
    ∀ t : ℕ,
      (∀ s : ℕ, s < t → γ s = δ s) →
        execution P C₀ γ t = execution P C₀ δ t
  | 0, _ => rfl
  | t + 1, h => by
      have hprev :
          execution P C₀ γ t = execution P C₀ δ t :=
        execution_eq_of_scheduler_agree (P := P) (C₀ := C₀) (t := t)
          (fun s hs => h s (Nat.lt_trans hs (Nat.lt_succ_self t)))
      have hstep : γ t = δ t := h t (Nat.lt_succ_self t)
      simp only [execution]
      rw [hprev, hstep]

/-- Finite first-hit extraction: if `G 0` is false and `G` holds at some
positive time `≤ K`, then there is a first transition `t → t+1`, with `t<K`,
before which `G` has not occurred. -/
theorem exists_first_success_before_strong
    {K : ℕ} {G : ℕ → Prop}
    (h0 : ¬ G 0)
    (hex : ∃ t : ℕ, t < K ∧ G (t + 1)) :
    ∃ t : ℕ, t < K ∧ (∀ s : ℕ, s ≤ t → ¬ G s) ∧ G (t + 1) := by
  classical
  have hexm : ∃ m : ℕ, 0 < m ∧ m ≤ K ∧ G m := by
    rcases hex with ⟨t, htK, hG⟩
    exact ⟨t + 1, by omega, by omega, hG⟩
  let m := Nat.find hexm
  have hm : 0 < m ∧ m ≤ K ∧ G m := Nat.find_spec hexm
  refine ⟨m - 1, by omega, ?_, ?_⟩
  · intro s hs hGs
    by_cases hs0 : s = 0
    · exact h0 (by simpa [hs0] using hGs)
    · have hspos : 0 < s := Nat.pos_of_ne_zero hs0
      have hsleK : s ≤ K := by omega
      have hsPm : 0 < s ∧ s ≤ K ∧ G s := ⟨hspos, hsleK, hGs⟩
      have hmin : m ≤ s := Nat.find_min' hexm hsPm
      omega
  · have hm_eq : m - 1 + 1 = m := by omega
    simpa [hm_eq] using hm.2.2

/-- Convert a deterministic scheduler that agrees with a finite prefix into
equality of the two selection-count notions. -/
theorem selectionCount_eq_prefixSelectionCount_of_prefix
    {K : ℕ} {γ : DetScheduler n} {σ : SchedulerPrefix n K}
    (hγ : ∀ i : Fin K, γ i.val = σ i) (a : Fin n) :
    selectionCount γ a K = prefixSelectionCount σ a := by
  classical
  unfold selectionCount prefixSelectionCount
  let A : Finset (Fin K) :=
    (Finset.univ.filter fun i : Fin K => prefixSelectedAt σ a i)
  have himage :
      A.image (fun i : Fin K => i.val) =
        ((Finset.range K).filter fun t => selectedAt γ a t) := by
    ext t
    constructor
    · intro ht
      rw [Finset.mem_image] at ht
      rcases ht with ⟨i, hiA, hit⟩
      subst t
      rw [Finset.mem_filter] at hiA
      rw [Finset.mem_filter]
      refine ⟨by simpa using i.isLt, ?_⟩
      simpa [selectedAt, prefixSelectedAt, hγ i] using hiA.2
    · intro ht
      rw [Finset.mem_filter] at ht
      refine Finset.mem_image.mpr ?_
      refine ⟨⟨t, by simpa using ht.1⟩, ?_, rfl⟩
      rw [Finset.mem_filter]
      refine ⟨Finset.mem_univ _, ?_⟩
      simpa [selectedAt, prefixSelectedAt, hγ ⟨t, by simpa using ht.1⟩] using ht.2
  rw [← himage]
  rw [Finset.card_image_of_injective]
  intro i j hij
  exact Fin.ext hij

namespace Probability

variable {Q X Y : Type*} {n : ℕ}

/-- Support characterization for the coupled scheduler-trace distribution.

A supported trace state is generated by some deterministic scheduler `γ` that
agrees with the stored finite prefix. Its configuration component is the
deterministic execution along that prefix, and its hit flag is exactly the
accumulated finite-prefix hit flag. -/
theorem schedulerTraceDist_support_spec
    (P : Protocol Q X Y) (hn : 2 ≤ n)
    (C₀ : Config Q X n) (Goal : Config Q X n → Prop) :
    ∀ {K : ℕ} (S : SchedulerTraceState Q X n K),
      S ∈ (schedulerTraceDist P hn C₀ Goal K).support →
        ∃ γ : DetScheduler n,
          (∀ i : Fin K, γ i.val = S.2 i) ∧
          S.1.1 = execution P C₀ γ K ∧
          S.1.2 =
            @decide
              (Goal C₀ ∨
                ∃ t : ℕ, t < K ∧ Goal (execution P C₀ γ (t + 1)))
              (Classical.propDecidable _)
  | 0, S, hSupp => by
      classical
      rw [schedulerTraceDist, PMF.support_pure] at hSupp
      subst S
      let z : Fin n := ⟨0, by omega⟩
      let γ : DetScheduler n := fun _ => (z, z)
      refine ⟨γ, ?_, ?_, ?_⟩
      · intro i
        exact Fin.elim0 i
      · rfl
      · by_cases hG : Goal C₀ <;> simp [hG]
  | K + 1, S, hSupp => by
      classical
      rw [schedulerTraceDist, PMF.mem_support_bind_iff] at hSupp
      rcases hSupp with ⟨T, hT, hStep⟩
      rw [schedulerTraceStepDist, PMF.support_map] at hStep
      rcases hStep with ⟨p, _hp, hpEq⟩
      subst S
      rcases schedulerTraceDist_support_spec
          (P := P) (hn := hn) (C₀ := C₀) (Goal := Goal)
          (K := K) T hT with
        ⟨γ₀, hγ₀, hC₀, hFlag₀⟩

      let z : Fin n := ⟨0, by omega⟩
      let γ : DetScheduler n := fun s =>
        if hs : s < K then γ₀ s
        else if hsK : s = K then p
        else (z, z)

      have hγ_lt : ∀ s : ℕ, s < K → γ s = γ₀ s := by
        intro s hs
        simp [γ, hs]

      have hγK : γ K = p := by
        simp [γ]

      have hExecK :
          execution P C₀ γ K = execution P C₀ γ₀ K := by
        apply execution_eq_of_scheduler_agree
        intro s hs
        exact hγ_lt s hs

      have hExecOld :
          ∀ m : ℕ, m ≤ K →
            execution P C₀ γ₀ m = execution P C₀ γ m := by
        intro m hm
        apply execution_eq_of_scheduler_agree
        intro s hs
        have hsK : s < K := lt_of_lt_of_le hs hm
        exact (hγ_lt s hsK).symm

      let Cnext : Config Q X n := T.1.1.step P p.1 p.2

      have hCnext :
          Cnext = execution P C₀ γ (K + 1) := by
        calc
          Cnext = T.1.1.step P p.1 p.2 := rfl
          _ = (execution P C₀ γ₀ K).step P p.1 p.2 := by rw [hC₀]
          _ = (execution P C₀ γ K).step P (γ K).1 (γ K).2 := by
                rw [← hExecK, hγK]
          _ = execution P C₀ γ (K + 1) := rfl

      have hprefix :
          ∀ i : Fin (K + 1),
            γ i.val =
              (@Fin.snoc K (fun _ => Fin n × Fin n) T.2 p) i := by
        intro i
        refine Fin.lastCases ?hLast ?hCast i
        · simp [γ]
        · intro j
          simp [γ, j.isLt, hγ₀ j]

      have hOldEq :
          (Goal C₀ ∨
              ∃ t : ℕ, t < K ∧ Goal (execution P C₀ γ₀ (t + 1))) ↔
            (Goal C₀ ∨
              ∃ t : ℕ, t < K ∧ Goal (execution P C₀ γ (t + 1))) := by
        constructor
        · intro h
          rcases h with hG0 | ⟨t, htK, htG⟩
          · exact Or.inl hG0
          · exact Or.inr
              ⟨t, htK, by
                have heq := hExecOld (t + 1) (by omega)
                simpa [heq] using htG⟩
        · intro h
          rcases h with hG0 | ⟨t, htK, htG⟩
          · exact Or.inl hG0
          · exact Or.inr
              ⟨t, htK, by
                have heq := hExecOld (t + 1) (by omega)
                simpa [heq] using htG⟩

      let Old : Prop :=
        Goal C₀ ∨
          ∃ t : ℕ, t < K ∧ Goal (execution P C₀ γ (t + 1))

      have hFlagOld : T.1.2 = decide Old := by
        by_cases hOld₀ :
          Goal C₀ ∨
            ∃ t : ℕ, t < K ∧ Goal (execution P C₀ γ₀ (t + 1))
        · have hOld : Old := hOldEq.mp hOld₀
          have hT : T.1.2 = true := by
            simpa [hOld₀] using hFlag₀
          simpa [Old, hOld] using hT
        · have hOld : ¬ Old := by
            intro h
            exact hOld₀ (hOldEq.mpr h)
          have hT : T.1.2 = false := by
            simpa [hOld₀] using hFlag₀
          simpa [Old, hOld] using hT

      let Target : Prop :=
        Goal C₀ ∨
          ∃ t : ℕ, t < K + 1 ∧ Goal (execution P C₀ γ (t + 1))

      have hTarget :
          (Old ∨ Goal Cnext) ↔ Target := by
        constructor
        · intro h
          rcases h with hOld | hNew
          · rcases hOld with hG0 | ⟨t, htK, htG⟩
            · exact Or.inl hG0
            · exact Or.inr ⟨t, by omega, htG⟩
          · exact Or.inr
              ⟨K, by omega, by simpa [Cnext, hCnext] using hNew⟩
        · intro h
          rcases h with hG0 | ⟨t, htK, htG⟩
          · exact Or.inl (Or.inl hG0)
          · by_cases htOld : t < K
            · exact Or.inl (Or.inr ⟨t, htOld, htG⟩)
            · have htEq : t = K := by omega
              subst t
              exact Or.inr (by simpa [Cnext, hCnext] using htG)

      refine ⟨γ, ?_, ?_, ?_⟩
      · simpa using hprefix
      · simpa [Cnext] using hCnext
      · change
            (T.1.2 || decide (Goal Cnext)) =
              @decide Target (Classical.propDecidable Target)
        rw [hFlagOld]
        by_cases hOld : Old
        · have hT : Target := hTarget.mp (Or.inl hOld)
          simp [hOld, hT]
        · by_cases hNew : Goal Cnext
          · have hT : Target := hTarget.mp (Or.inr hNew)
            simp [hOld, hNew, hT]
          · have hT : ¬ Target := by
              intro hT
              rcases hTarget.mpr hT with hOld' | hNew'
              · exact hOld hOld'
              · exact hNew hNew'
            simp [hOld, hNew, hT]

end Probability

/-- Stronger first-hit reconstruction for the concrete drain goal.

Besides `SomeAgentAwakeBeforeK`, this records that the chosen hit time is the
first hit, which is exactly what is needed to invoke a no-wake-prefix load
certificate up to that pre-wake time. -/
theorem schedulerTraceDist_support_hit_true_to_first_someAgentAwakeBeforeK
    {n Rmax Emax Dmax K : ℕ}
    (hn : 0 < n) (hn2 : 2 ≤ n)
    (C₀ : Config (AgentState n) Opinion n)
    (hInitNoAwake : ¬ SomeAgentAwake C₀)
    (S : Probability.SchedulerTraceState (AgentState n) Opinion n K)
    (hSupp :
      S ∈
        (Probability.schedulerTraceDist
          (PEMProtocol n 1 Rmax Emax Dmax hn) hn2 C₀ SomeAgentAwake K).support)
    (hHit : S.1.2 = true) :
    ∃ γ : DetScheduler n,
      (∃ t : ℕ, t < K ∧
        (∀ s : ℕ, s ≤ t →
          ¬ SomeAgentAwake
            (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ s)) ∧
        SomeAgentAwake
          (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ (t + 1))) ∧
      (∀ a : Fin n,
        selectionCount γ a K = prefixSelectionCount S.2 a) := by
  classical
  rcases Probability.schedulerTraceDist_support_spec
      (P := PEMProtocol n 1 Rmax Emax Dmax hn)
      (hn := hn2) (C₀ := C₀) (Goal := SomeAgentAwake)
      (K := K) S hSupp with
    ⟨γ, hγ, _hConfig, hFlag⟩

  let HitProp : Prop :=
    SomeAgentAwake C₀ ∨
      ∃ t : ℕ, t < K ∧
        SomeAgentAwake
          (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ (t + 1))

  have hHitProp : HitProp := by
    have hdec : decide HitProp = true := by
      simpa [HitProp] using hFlag.symm.trans hHit
    by_cases h : HitProp
    · exact h
    · simp [HitProp, h] at hdec

  have hex :
      ∃ t : ℕ, t < K ∧
        SomeAgentAwake
          (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ (t + 1)) := by
    rcases hHitProp with hAwake0 | hLater
    · exact False.elim (hInitNoAwake hAwake0)
    · exact hLater

  have hfirst :=
    exists_first_success_before_strong
      (K := K)
      (G := fun m : ℕ =>
        SomeAgentAwake
          (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ m))
      (by simpa [execution] using hInitNoAwake)
      hex

  refine ⟨γ, hfirst, ?_⟩
  intro a
  exact selectionCount_eq_prefixSelectionCount_of_prefix hγ a

/-- Requested weaker reconstruction: a supported true hit flag gives a
deterministic scheduler witnessing `SomeAgentAwakeBeforeK`, and the deterministic
selection counts agree with the stored scheduler prefix. -/
theorem schedulerTraceDist_support_hit_true_to_someAgentAwakeBeforeK
    {n Rmax Emax Dmax K : ℕ}
    (hn : 0 < n) (hn2 : 2 ≤ n)
    (C₀ : Config (AgentState n) Opinion n)
    (hInitNoAwake : ¬ SomeAgentAwake C₀)
    (S : Probability.SchedulerTraceState (AgentState n) Opinion n K)
    (hSupp :
      S ∈
        (Probability.schedulerTraceDist
          (PEMProtocol n 1 Rmax Emax Dmax hn) hn2 C₀ SomeAgentAwake K).support)
    (hHit : S.1.2 = true) :
    ∃ γ : DetScheduler n,
      SomeAgentAwakeBeforeK
        (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ K ∧
      (∀ a : Fin n,
        selectionCount γ a K = prefixSelectionCount S.2 a) := by
  rcases schedulerTraceDist_support_hit_true_to_first_someAgentAwakeBeforeK
      (hn := hn) (hn2 := hn2) (C₀ := C₀)
      (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
      hInitNoAwake S hSupp hHit with
    ⟨γ, hfirst, hcount⟩
  rcases hfirst with ⟨t, htK, hNoPrefix, hAwakeNext⟩
  refine ⟨γ, ?_, hcount⟩
  exact ⟨t, htK, hNoPrefix t le_rfl, hAwakeNext⟩

/-- Final drain/no-wake binomial tail, using the no-wake-prefix load certificate
as an external hypothesis.

The `hLoadCert` hypothesis is the codex-proved deterministic connector:
on any deterministic no-wake prefix from the fixed fresh start `C₀`, the
wake-load certificate holds at the endpoint of that prefix. -/
theorem drain_probHitWithin_le_choose
    {n Rmax Emax Dmax K d : ℕ}
    (hn : 0 < n) (hn2 : 2 ≤ n) (hd_pos : 0 < d) (hd : d ≤ Dmax)
    {C₀ : Config (AgentState n) Opinion n}
    (hAll : AllAgentsResetting C₀)
    (hLoadCert :
      ∀ γ : DetScheduler n, ∀ T : ℕ,
        (∀ s : ℕ, s ≤ T →
          ¬ SomeAgentAwake
            (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ s)) →
        WakeLoadCertificateAt d γ T
          (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ T)) :
    Probability.ProbHitWithin
        (PEMProtocol n 1 Rmax Emax Dmax hn) hn2 C₀ SomeAgentAwake K
      ≤
        (n : ENNReal) * (Nat.choose K d : ENNReal) *
          (((2 : ENNReal) * (n : ENNReal)⁻¹) ^ d) := by
  classical
  have hDmax : 0 < Dmax := Nat.lt_of_lt_of_le hd_pos hd
  have hInitNoAwake : ¬ SomeAgentAwake C₀ := by
    rintro ⟨a, ha⟩
    exact ha (hAll a)

  apply drain_probHitWithin_le_choose_of_support_cert
    (hn := hn) (hn2 := hn2)
    (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
    (K := K) (d := d) (C₀ := C₀)

  intro S hSupp hHit
  rcases schedulerTraceDist_support_hit_true_to_first_someAgentAwakeBeforeK
      (hn := hn) (hn2 := hn2) (C₀ := C₀)
      (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
      hInitNoAwake S hSupp hHit with
    ⟨γ, hfirst, hcount⟩
  rcases hfirst with ⟨t, htK, hNoPrefix, hAwakeNext⟩

  have hCertAt :
      WakeLoadCertificateAt d γ t
        (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ t) :=
    hLoadCert γ t hNoPrefix

  have hWitness :
      SomeAgentAwakeStepWitness γ t
        (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ t)
        (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ (t + 1)) := by
    simpa [PEMProtocol, execution] using
      someAgentAwakeStepWitness_PEM
        (n := n) (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
        hn hDmax γ t
        (execution (PEMProtocol n 1 Rmax Emax Dmax hn) C₀ γ t)

  rcases hWitness (hNoPrefix t le_rfl) hAwakeNext with ⟨w, hTimeout⟩

  have hCertified :
      CertifiedWakeBeforeK
        (PEMProtocol n 1 Rmax Emax Dmax hn) d C₀ γ K := by
    exact ⟨t, htK, w, hCertAt, hTimeout⟩

  rcases certified_wake_before_K_implies_high_load
      (P := PEMProtocol n 1 Rmax Emax Dmax hn)
      (d := d) (C₀ := C₀) (γ := γ) (K := K)
      hCertified with
    ⟨a, ha⟩

  change ∃ a : Fin n, d ≤ prefixSelectionCount S.2 a
  exact ⟨a, by simpa [hcount a] using ha⟩

/-- Unconditional drain/no-wake binomial tail from a fresh all-Resetting start.

The deterministic load-certificate hypothesis in
`drain_probHitWithin_le_choose` is discharged by the proven PEM no-wake-prefix
certificate. -/
theorem drain_probHitWithin_le_choose_unconditional
    {n Rmax Emax Dmax K d : ℕ}
    (hn : 0 < n) (hn2 : 2 ≤ n) (hd_pos : 0 < d) (hd : d ≤ Dmax)
    {C₀ : Config (AgentState n) Opinion n}
    (hAll : AllAgentsResetting C₀)
    (hDormantBudget :
      ∀ a : Fin n, (C₀ a).1.resetcount = 0 → d ≤ (C₀ a).1.delaytimer) :
    Probability.ProbHitWithin
        (PEMProtocol n 1 Rmax Emax Dmax hn) hn2 C₀ SomeAgentAwake K
      ≤
        (n : ENNReal) * (Nat.choose K d : ENNReal) *
          (((2 : ENNReal) * (n : ENNReal)⁻¹) ^ d) := by
  have hDmax : 0 < Dmax := Nat.lt_of_lt_of_le hd_pos hd
  apply drain_probHitWithin_le_choose
    (hn := hn) (hn2 := hn2) (hd_pos := hd_pos) (hd := hd)
    (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
    (K := K) (d := d) (C₀ := C₀) hAll
  intro γ T hNoAwakePrefix
  exact
    wake_load_certificate_PEM_on_no_wake_prefix
      (n := n) (Rmax := Rmax) (Emax := Emax) (Dmax := Dmax)
      (K := T) (d := d) hn hDmax hd C₀ γ hAll
      hDormantBudget hNoAwakePrefix T le_rfl

end SSEM
