/-
Copyright (c) 2026 Xiang Huang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xiang Huang
-/
import Tri.Assembly
import Tri.BandReturn
import Tri.BandRung
import Tri.Basic
import Tri.BudgetArith
import Tri.Bracket
import Tri.Chain
import Tri.ProductivityFloor
import Tri.Compose
import Tri.Emulation
import Tri.Counting
import Tri.Decay
import Tri.Direction
import Tri.DirectionProgress
import Tri.Drift
import Tri.FiveJumpMGF
import Tri.Endgame
import Tri.EscapeSplit
import Tri.FinalN0
import Tri.Freeze
import Tri.Hoeffding
import Tri.Kernel
import Tri.Ladder
import Tri.SameHorizon
import Tri.Lemma14Leaf
import Tri.Lemma15Window
import Tri.Lemma15Numeric
import Tri.Lemma15Split
import Tri.Lemma15Prefix
import Tri.Lemma15Glue
import Tri.HitProbMono
import Tri.BellmanDomination
import Tri.Lemma15Domination
import Tri.Lemma15Assembly
import Tri.Lemma16Exponent
import Tri.Lemma16Urn
import Tri.Lemma16ActiveCount
import Tri.Lemma16ActivationClock
import Tri.Lemma16Label
import Tri.Lemma15Anchor
import Tri.Lazy
import Tri.Main
import Tri.Phase1Inhabit
import Tri.Phase1Ladder
import Tri.Phase1Corrected
import Tri.Phase1Refactored
import Tri.Phase1Staged
import Tri.Phase2BridgeBuffered
import Tri.Phase2Additive
import Tri.Phase2AdditiveBudget
import Tri.Phase2Budget
import Tri.Phase2CRN
import Tri.Phase2Contract
import Tri.Phase2Inhabit
import Tri.Phase2Reconciled
import Tri.Phase3CRN
import Tri.Phase3Feller
import Tri.Phase3Horizon
import Tri.Phase3Reconciled
import Tri.Phase3Stop
import Tri.PhaseGlue
import Tri.ProdBound
import Tri.Progress
import Tri.Reconciled
import Tri.ReconciledRegions
import Tri.Regions
import Tri.Ruin
import Tri.Rung
import Tri.StageErrors
import Tri.Schedule
import Tri.Statement
import Tri.Step
import Tri.Smoke
import Tri.Phase1Assembly
import Tri.Theorem1bFinal
import Tri.Foray
import Tri.Theorem1a
import Tri.Phase0
import Tri.BiMolecular
import Tri.BiKernel
import Tri.BiStep
import Tri.HeavyBKernel
import Tri.HeavyBEmulation
import Tri.HeavyBTrace
import Tri.HeavyBDirection
import Tri.HeavyBExpect
import Tri.HeavyBPotential
import Tri.HeavyBBand
import Tri.HeavyBWindowTail
import Tri.HeavyBChain
import Tri.HeavyBInvariant
import Tri.HeavyBResolution
import Tri.HeavyBFeller
import Tri.HeavyBBandReturn
import Tri.HeavyBRung
import Tri.HeavyBProductiveFloor
import Tri.HeavyBProductiveTail
import Tri.HeavyBClockTrace
import Tri.HeavyBClockNormal
import Tri.HeavyBClockBlank
import Tri.HeavyBStaged
import Tri.HeavyBClockProjection
import Tri.HeavyBClockConstants
import Tri.HeavyBClockRung
import Tri.HeavyBBandRung
import Tri.HeavyBMiddleConstants
import Tri.HeavyBEarlyLadder
import Tri.HeavyBConstantGap
import Tri.HeavyBLateLadder
import Tri.HeavyBFinalConsensus
import Tri.HeavyBAssembly
import Tri.HeavyBHeadline
import Tri.BiChain
import Tri.DoubleBInvariant
import Tri.DoubleBTrace
import Tri.DoubleBResolution
import Tri.DoubleBFeller
import Tri.DoubleBDirection
import Tri.Theorem2
import Tri.Theorem4Statement
import Tri.ByzantineRateAdapter
import Tri.ByzantinePhase1Rung
import Tri.StoppedHitTransfer
import Tri.ByzantineJointLaw
import Tri.ByzantinePhase1StochOrder
import Tri.ByzantinePhase1Productive
import Tri.ByzantinePhase1RawRung
import Tri.ByzantinePhase1EntryBridge
import Tri.ByzantinePhase2ClockFloor
import Tri.ByzantinePhase2RawRung
import Tri.ByzantinePhase1Ladder
import Tri.RelaxedProductiveMonotone
import Tri.ByzantinePhase1Unconditional
import Tri.ByzantinePhase2Rung
import Tri.ByzantinePhase2Bridge
import Tri.ByzantinePhase2Ladder
import Tri.DoubleBAssembly
import Tri.DoubleBBandReturn
import Tri.DoubleBBandParams
import Tri.DoubleBBandRung
import Tri.DoubleBClockSplitArithmetic
import Tri.DoubleBClockMass
import Tri.DoubleBClockTrace
import Tri.MaskedCounting
import Tri.DoubleBClockNormal
import Tri.DoubleBClockBlank
import Tri.DoubleBClockProjection
import Tri.DoubleBClockRung
import Tri.DoubleBClockConstants
import Tri.DoubleBDirectionConstants
import Tri.DoubleBEarlyLadder
import Tri.DoubleBConstantGap
import Tri.DoubleBLateLadder
import Tri.DoubleBLateConstants
import Tri.DoubleBLateBudget
import Tri.DoubleBMiddleConstants
import Tri.DoubleBFinalConsensus
import Tri.DoubleBHeadline
import Tri.SingleBCreationTailY
import Tri.SingleBGapRecovery
import Tri.SingleBResolutionPort
import Tri.SingleBDirection
import Tri.SingleBBandKernel
import Tri.SingleBWindowTail
import Tri.SingleBStaged
import Tri.SingleBProductiveTail
import Tri.SingleBLevelPhaseStructural
import Tri.SingleBLateDirection
import Tri.SingleBLateRung
import Tri.SingleBLateLadder
import Tri.SingleBLateConcrete
import Tri.SingleBHighCapBridge
import Tri.SingleBFinalConsensus
import Tri.SingleBAssembly
import Tri.SingleBFeller
import Tri.SingleBBandRung
import Tri.SingleBClockTrace
import Tri.SingleBClockNormal
import Tri.SingleBClockBlank
import Tri.SingleBClockProjection
import Tri.SingleBClockConstants
import Tri.SingleBClockRung
import Tri.RelaxedKernel
import Tri.RelaxedStep
import Tri.RelaxedOdds
import Tri.RelaxedChain
import Tri.RelaxedDrift
import Tri.RelaxedFeller
import Tri.RelaxedCounting
import Tri.RelaxedProductivity
import Tri.RelaxedStrictOdds
import Tri.RelaxedDirectionParams
import Tri.RelaxedProgress
import Tri.RelaxedDirection
import Tri.RelaxedBand
import Tri.RelaxedBandMonitor
import Tri.RelaxedBandRung
import Tri.RelaxedBandPhysicalRung
import Tri.RelaxedBandPhysicalLadder
import Tri.RelaxedBandPhysicalSchedule
import Tri.RelaxedBandUniformSchedule
import Tri.RelaxedBandAdaptiveSchedule
import Tri.RelaxedBandErrorConstants
import Tri.RelaxedBandAdaptiveError
import Tri.RelaxedBandScalarConstructor
import Tri.RelaxedTheorem3
import Tri.RelaxedTheorem3Paper
import Tri.MultiState
import Tri.MultiGapEdge
import Tri.MultiKernel
import Tri.MultiAggregation
import Tri.MultiStep
import Tri.MultiFiber
import Tri.MultiBinaryEnvelope
import Tri.BinaryMonotone
import Tri.MultiFiniteHorizonEnvelope
import Tri.MultiFiniteHorizonConsensus
import Tri.MultiPairGap
import Tri.MultiThirdParty
import Tri.MultiPairBias
import Tri.MultiStrictBias
import Tri.MultiPairLedger
import Tri.MultiPairJump
import Tri.MultiPairMass
import Tri.MultiPairSuper
import Tri.MultiPairStop
import Tri.MultiProductive
import Tri.MultiProductiveClock
import Tri.MultiProductiveClockConstants
import Tri.MultiProductiveEmbedded
import Tri.MultiProductivePair
import Tri.MultiProductiveTimeChange
import Tri.MultiProductiveTimeChangePaper
import Tri.MultiProductivePhase0Stage
import Tri.MultiProductivePhase0Ladder
import Tri.MultiProductivePhase0Unconditional
import Tri.MultiProductivePhase0LadderUnconditional
import Tri.MultiTheorem1bHandoff
import Tri.MultiTheorem5
import Tri.MultiTheorem5Error
import Tri.MultiTheorem5Unconditional
import Tri.MultiProductiveLinear
import Tri.MultiProductiveProgress
import Tri.MultiProductiveProgressStep
import Tri.MultiProductiveProgressStop
import Tri.MultiProductiveProgressJoint
import Tri.MultiProductiveProgressConstants
import Tri.MultiProductiveProgressLocal
import Tri.MultiProductiveProgressLocalStop
import Tri.MultiProductiveProgressLocalJoint
import Tri.MultiProductiveProgressLocalConstants
import Tri.MultiProductiveProperProgress
import Tri.MultiProductiveProperProgressStop
import Tri.MultiProductiveProperProgressConstants
import Tri.MultiProductiveStageProgress
import Tri.MultiProductiveStageDeadline
import Tri.MultiProductiveInvolvingInvariant
import Tri.MultiProductiveStageLive
import Tri.MultiProductiveStageCompletion
import Tri.MultiProductiveStageSafety
import Tri.MultiProductiveProperStage
import Tri.MultiProductiveStateDependent
import Tri.MultiProductiveStateScalar
import Tri.MultiProductiveAmplification
import Tri.LazyHitting
import Tri.MultiProductiveAmplificationLift
import Tri.MultiProductiveAmplificationUnconditional
import Tri.InfectionKernel
import Tri.InfectionHandoff
import Tri.InfectionFullActive
import Tri.InfectionActivation
import Tri.InfectionActivationBand
import Tri.InfectionActiveCount
import Tri.InfectionActiveConstants
import Tri.InfectionReactionBias
import Tri.InfectionReactionPotential
import Tri.InfectionReactionExp
import Tri.InfectionReactionSafety
import Tri.InfectionActivationConstants
import Tri.InfectionActivationEarly
import Tri.InfectionActivationBudget
import Tri.InfectionReveal
import Tri.InfectionRevealPrefix
import Tri.InfectionRevealUrn
import Tri.InfectionRevealPhysicalAtoms
import Tri.InfectionRevealPhysicalUpdate
import Tri.InfectionRevealPhysicalStep
import Tri.InfectionRevealPhysicalBatch
import Tri.InfectionRevealPhysicalPath
import Tri.InfectionRevealPhysicalLaw
import Tri.InfectionRevealPhysicalPairLaw
import Tri.InfectionRevealPhysicalWordLaw
import Tri.InfectionRevealPhysicalFirstK
import Tri.InfectionRevealTwoSequential
import Tri.InfectionRevealPhysicalMixture
import Tri.InfectionRevealPhysicalTimeChange
import Tri.InfectionRevealPrefixTimeChange
import Tri.InfectionRevealPhysicalFirstKTimeChange
import Tri.InfectionRevealTrace
import Tri.TimeChangeHitting
import Tri.InfectionRevealPhysicalHitting
import Tri.Lemma16PhysicalUrn
import Tri.Lemma16CountedPath
import Tri.Lemma17CountedPath
import Tri.Lemma17JointTails
import Tri.Lemma17StageDeterministic
import Tri.Lemma17StageAssembly
import Tri.Lemma17LabelPath
import Tri.Lemma17LabelTail
import Tri.Lemma17JointLabelTail
import Tri.Lemma17PoolTail
import Tri.Lemma17InactiveMajorityTail
import Tri.InfectionRevealPhysicalUrnPotential
import Tri.Lemma17StageMajority
import Tri.Lemma17DoublingClock
import Tri.Lemma17PaperStage
import Tri.Lemma17PhysicalStage
import Tri.Lemma17Error
import Tri.StagedKernel
import Tri.StagedLazyHitting
import Tri.HitThenReaches
import Tri.Lemma17StageRange
import Tri.Lemma17StagePotential
import Tri.Lemma17Ladder
import Tri.Lemma17CustomLanding
import Tri.Lemma17FixedLanding
import Tri.Lemma16To17FixedLanding
import Tri.Lemma17FixedLandingTo18
import Tri.Lemma17FixedLandingTo19
import Tri.Lemma16To17
import Tri.Lemma18Deterministic
import Tri.Lemma18StageAssembly
import Tri.Lemma18BlockTail
import Tri.Lemma18PaperStage
import Tri.Lemma18Error
import Tri.Lemma18PhysicalStage
import Tri.Lemma17To18
import Tri.Lemma16To19
import Tri.Lemma19Stage
import Tri.Lemma19PaperStage
import Tri.Lemma19PhysicalStage
import Tri.Lemma19LateStage
import Tri.FiniteHorizonUnion
import Tri.Lemma19UrnLabel
import Tri.Lemma19FullPoolLabel
import Tri.Lemma19FullPoolJoint
import Tri.Lemma19ReactionSafety
import Tri.Lemma19BudgetStage
import Tri.Lemma18To19
import Tri.Lemma18To19Budget
import Tri.InfectionActivationError
import Tri.Lemma16To19Error
import Tri.Lemma16To19ErrorConditions
import Tri.Lemma19Parameters
import Tri.InfectionInitialParams
import Tri.Theorem6Parameters
import Tri.Lemma16To19Feasibility
import Tri.Lemma19Ladder
import Tri.Lemma18To19Ladder
import Tri.Lemma17To19Ladder
import Tri.Lemma16To19Corrected
import Tri.Lemma16To19CorrectedError
import Tri.Lemma16To19CorrectedHeadline
import Tri.Lemma19FixedWindow
import Tri.Lemma19FixedParameters
import Tri.Lemma16To19Headline
import Tri.Theorem6ActivationHandoff
import Tri.InfectionTriEntry
import Tri.PhysicalStageClock
import Tri.Lemma16To19Clock
import Tri.Lemma16To19CorrectedClock
import Tri.InfectionPhysicalClockProjection
import Tri.Lemma16To19CorrectedRaw
import Tri.Lemma16To19Raw
import Tri.ByzantineKernel
import Tri.ByzantineAdaptive
import Tri.ByzantineEntry
import Tri.ByzantinePostEntry
import Tri.RelaxedBinaryMonotone
import Tri.StoppedHitMonotone
import Tri.ByzantinePhase2BufferedRung
import Tri.Theorem4Entry
import Tri.Theorem4EntryUnconditional
import Tri.Theorem4EntryHeadline
import Tri.ByzantineRelaxedBridge
import Tri.PaperCorollary1
import Tri.PaperCorollary2
import Tri.PaperCorollary3
import Tri.Corollary3Monotone
import Tri.Phase3Level
import Tri.Phase3Productive
import Tri.Phase3RawCompletion
import Tri.PaperLemma2
import Tri.PaperLemma3
import Tri.PaperLemma4
import Tri.PaperLemma5
import Tri.PaperLemma6
import Tri.PaperLemma7
import Tri.PaperLemma8
import Tri.RelaxedProductiveTimeChange
import Tri.PaperLemma9
import Tri.PaperLemma10
import Tri.PaperLemma11
import Tri.PaperLemma12
import Tri.PaperLemma12Unconditional
import Tri.PaperLemma13
import Tri.PaperLemma14
import Tri.PaperLemma15
import Tri.SingleBKernel
import Tri.SingleBMass
import Tri.SingleBTrace
import Tri.SingleBLevel
import Tri.SingleBCreation
import Tri.SingleBCreationStep
import Tri.SingleBBudget
import Tri.SingleBCreationTail
import Tri.BiKernel
import Tri.Theorem6FixedPaper

import Tri.SingleBCoReturn
import Tri.SingleBWideClock
import Tri.SingleBLevelPhase
import Tri.SingleBGapRung
import Tri.SingleBEarlyLadder
import Tri.SingleBMiddleConstants
import Tri.SingleBLateRung
import Tri.SingleBLateLadder
import Tri.SingleBHeadline
import Tri.InhabitationWitnesses

/-!
# Tri-molecular approximate-majority formalization

This umbrella module imports the active proof graph for the paper-level binary,
Byzantine, multi-species, and activation theorems.  The public headline
declarations include `Tri.Byzantine.theorem4_entry`, `Tri.Multi.theorem5`,
`Tri.Byzantine.lemma8`, and `Tri.Multi.lemma12_unconditional`.
-/
