/-
Ripple.BoundedUniversality.BGP.DynamicGate
----------------------
Framework v2: the exp-affine dynamic-gate iterator
(notes/sec3-redesign-2026-06-11.md, v3 design, approved 2026-06-11).

Mechanism: the channel gates are exponentials of −μ·(nodal pulse
power), generated by rational polynomial ODEs.  With μ(0) = 0 the
gate initial value is e⁰ = 1 — RATIONAL — which is what makes the
whole system a rational PIVP (any μ(0) > 0 start would give a
transcendental initial gate value).  The precision μ grows linearly
(μ' = c₀) and the gain α grows exponentially (α' = c₁ α):

  z-gate  bGateZ(t) = exp(−μ(t) · rPulse L t)   — off-phase ≤ e^{−μ·2^{-L}},
                                                   active ≥ e^{−μ·4^{-L}}
  u-gate  bGateU(t) = exp(−μ(t) · qPulse L t)   — mirrored
  ż_i = α · bGateZ · (F(u)_i − z_i),   u̇_i = α · bGateU · (z_i − u_i)

Per cycle j: contraction exp(−α_j e^{−μ̄_j 4^{-L}} · window) becomes
superexponentially strong; off-leak ~ ᾱ_j e^{−μ_j 2^{-L}} decays
exponentially once c₀·2^{-L} > c₁ — the dynamic cascade.  The first
cycles (μ ≈ 0) degenerate to the classic fixed-gate iterator, so the
fixed-gate lemmas (PhaseClock P1–P6) are the base case, not dead code.

`targeting_bound` and `hold_bound` apply VERBATIM with
φ := α·bGate (A := 1): no new analytic workhorses are needed — only
gate-value bounds (proved below) and the j-dependent cascade
(obligations V1–V4).
-/

import Ripple.BoundedUniversality.BGP.PhaseClock
import Mathlib

namespace Ripple.BoundedUniversality.BGP

open Real
open intervalIntegral

/-! ## Gate values -/

/-- z-channel dynamic gate value: `exp(−m · rPulse L t)`. -/
noncomputable def bGateZ (L : ℕ) (m t : ℝ) : ℝ :=
  Real.exp (-(m * rPulse L t))

/-- u-channel dynamic gate value: `exp(−m · qPulse L t)`. -/
noncomputable def bGateU (L : ℕ) (m t : ℝ) : ℝ :=
  Real.exp (-(m * qPulse L t))

theorem bGateZ_pos (L : ℕ) (m t : ℝ) : 0 < bGateZ L m t := Real.exp_pos _

theorem bGateU_pos (L : ℕ) (m t : ℝ) : 0 < bGateU L m t := Real.exp_pos _

theorem bGateZ_le_one (L : ℕ) {m : ℝ} (hm : 0 ≤ m) (t : ℝ) :
    bGateZ L m t ≤ 1 := by
  unfold bGateZ
  rw [Real.exp_le_one_iff]
  have := rPulse_nonneg L t
  nlinarith

theorem bGateU_le_one (L : ℕ) {m : ℝ} (hm : 0 ≤ m) (t : ℝ) :
    bGateU L m t ≤ 1 := by
  unfold bGateU
  rw [Real.exp_le_one_iff]
  have := qPulse_nonneg L t
  nlinarith

/-- Off-phase suppression for the z-gate: where `sin t ≤ 0`,
`bGateZ ≤ exp(−m · 2^{-L})` — exponentially small in `m`.  (The
nodal power `rPulse L t = ((1−sin t)/2)^L ≥ 2^{-L}` there.) -/
theorem bGateZ_le_offphase (L : ℕ) {m t : ℝ} (hm : 0 ≤ m)
    (h : Real.sin t ≤ 0) :
    bGateZ L m t ≤ Real.exp (-(m * (1/2)^L)) := by
  unfold bGateZ
  apply Real.exp_le_exp.mpr
  have hr : ((1:ℝ)/2)^L ≤ rPulse L t := by
    apply pow_le_pow_left₀ (by norm_num)
    linarith
  nlinarith

/-- Half-phase suppression for the z-gate: where `sin t ≤ 1/2`,
`bGateZ ≤ exp(−m · 4^{-L})`.  This is the weaker edge-window bound used
before and after the z-off middle interval. -/
theorem bGateZ_le_halfphase (L : ℕ) {m t : ℝ} (hm : 0 ≤ m)
    (h : Real.sin t ≤ (1 / 2 : ℝ)) :
    bGateZ L m t ≤ Real.exp (-(m * (1 / 4 : ℝ) ^ L)) := by
  unfold bGateZ
  apply Real.exp_le_exp.mpr
  have hr : ((1 : ℝ) / 4) ^ L ≤ rPulse L t := by
    unfold rPulse
    apply pow_le_pow_left₀
    · nlinarith [Real.sin_le_one t]
    · nlinarith [h]
  have hmul : m * ((1 : ℝ) / 4) ^ L ≤ m * rPulse L t :=
    mul_le_mul_of_nonneg_left hr hm
  nlinarith

/-- Active-window lower bound for the z-gate: where `sin t ≥ 1/2`,
`bGateZ ≥ exp(−m · 4^{-L})` — near 1 when `m·4^{-L}` is small.
(`rPulse L t ≤ 4^{-L}` there.) -/
theorem bGateZ_ge_active (L : ℕ) {m t : ℝ} (hm : 0 ≤ m)
    (h : (1:ℝ)/2 ≤ Real.sin t) :
    Real.exp (-(m * (1/4)^L)) ≤ bGateZ L m t := by
  unfold bGateZ
  apply Real.exp_le_exp.mpr
  have hr : rPulse L t ≤ ((1:ℝ)/4)^L := by
    unfold rPulse
    apply pow_le_pow_left₀
    · nlinarith [Real.sin_le_one t]
    · linarith
  nlinarith

/-- Mirrored bounds for the u-gate: where `sin t ≥ 0`,
`bGateU ≤ exp(−m·2^{-L})`; where `sin t ≤ −1/2`,
`bGateU ≥ exp(−m·4^{-L})`. -/
theorem bGateU_le_offphase (L : ℕ) {m t : ℝ} (hm : 0 ≤ m)
    (h : 0 ≤ Real.sin t) :
    bGateU L m t ≤ Real.exp (-(m * (1/2)^L)) := by
  unfold bGateU
  apply Real.exp_le_exp.mpr
  have hq : ((1:ℝ)/2)^L ≤ qPulse L t := by
    apply pow_le_pow_left₀ (by norm_num)
    linarith
  nlinarith

theorem bGateU_ge_active (L : ℕ) {m t : ℝ} (hm : 0 ≤ m)
    (h : Real.sin t ≤ -(1/2)) :
    Real.exp (-(m * (1/4)^L)) ≤ bGateU L m t := by
  unfold bGateU
  apply Real.exp_le_exp.mpr
  have hq : qPulse L t ≤ ((1:ℝ)/4)^L := by
    unfold qPulse
    apply pow_le_pow_left₀
    · nlinarith [Real.neg_one_le_sin t]
    · linarith
  nlinarith

/-! ## The dynamic iterator (v3 design) -/

/-- A solution of the dynamic-gate iterator on `ℝ^{2d+4}`: coordinates
`(s, c, μ, α, z, u)` with the oscillator solved exactly, precision
`μ' = c₀` from `μ(0) = 0`, gain `α' = c₁ α` from `α(0) = 1`, and the
channels gated by the exp-affine gates.  All vector-field data
rational once `c₀ c₁ : ℚ`; all initial data rational BECAUSE
`μ(0) = 0` forces the initial gate values to `1`. -/
structure DynIteratorSol (d : ℕ) (Fr : (Fin d → ℝ) → Fin d → ℝ)
    (A : ℚ) (L : ℕ) (c₀ c₁ : ℚ) (x₀ : Fin d → ℝ) where
  μ : ℝ → ℝ
  α : ℝ → ℝ
  z : ℝ → Fin d → ℝ
  u : ℝ → Fin d → ℝ
  init_μ : μ 0 = 0
  init_α : α 0 = 1
  init_z : z 0 = x₀
  init_u : u 0 = x₀
  cont_z : ∀ i : Fin d, Continuous fun t => z t i
  cont_u : ∀ i : Fin d, Continuous fun t => u t i
  ode_μ : ∀ t : ℝ, 0 ≤ t → HasDerivAt μ (c₀ : ℝ) t
  ode_α : ∀ t : ℝ, 0 ≤ t → HasDerivAt α ((c₁ : ℝ) * α t) t
  ode_z : ∀ (t : ℝ), 0 ≤ t → ∀ (i : Fin d),
    HasDerivAt (fun τ => z τ i)
      ((A : ℝ) * α t * bGateZ L (μ t) t * (Fr (u t) i - z t i)) t
  ode_u : ∀ (t : ℝ), 0 ≤ t → ∀ (i : Fin d),
    HasDerivAt (fun τ => u τ i)
      ((A : ℝ) * α t * bGateU L (μ t) t * (z t i - u t i)) t

/-- Forward constancy: zero derivative on `[0, ∞)` pins the value. -/
private theorem fwd_eq_of_deriv_zero
    (f : ℝ → ℝ)
    (hderiv : ∀ s : ℝ, 0 ≤ s → HasDerivAt f 0 s)
    (t : ℝ) (ht : 0 ≤ t) :
    f t = f 0 := by
  have hmono : ∀ (g : ℝ → ℝ), (∀ s : ℝ, 0 ≤ s → HasDerivAt g 0 s) →
      0 ≤ g 0 → 0 ≤ g t := by
    intro g hg h0
    have hm : MonotoneOn g (Set.Icc 0 t) := by
      apply monotoneOn_of_deriv_nonneg (convex_Icc 0 t)
      · intro x hx
        exact (hg x hx.1).continuousAt.continuousWithinAt
      · intro x hx
        rw [interior_Icc] at hx
        exact ((hg x hx.1.le).differentiableAt).differentiableWithinAt
      · intro x hx
        rw [interior_Icc] at hx
        rw [(hg x hx.1.le).deriv]
    have := hm (Set.left_mem_Icc.mpr ht) (Set.right_mem_Icc.mpr ht) ht
    linarith
  have h1 : 0 ≤ (fun s => f s - f 0) t := by
    apply hmono (fun s => f s - f 0)
    · intro s hs
      simpa using (hderiv s hs).sub_const (f 0)
    · simp
  have h2 : 0 ≤ (fun s => f 0 - f s) t := by
    apply hmono (fun s => f 0 - f s)
    · intro s hs
      have := (hderiv s hs).const_sub (f 0)
      simpa using this
    · simp
  simp only at h1 h2
  linarith

/-- μ is explicitly linear (uniqueness): `μ t = c₀ t`. -/
theorem DynIteratorSol.mu_eq {d : ℕ} {Fr : (Fin d → ℝ) → Fin d → ℝ}
    {A : ℚ} {L : ℕ} {c₀ c₁ : ℚ} {x₀ : Fin d → ℝ}
    (sol : DynIteratorSol d Fr A L c₀ c₁ x₀) :
    ∀ t : ℝ, 0 ≤ t → sol.μ t = (c₀ : ℝ) * t := by
  intro t ht
  have h := fwd_eq_of_deriv_zero (fun s => sol.μ s - (c₀ : ℝ) * s)
    (fun s hs => by
      have h1 := sol.ode_μ s hs
      have h2 : HasDerivAt (fun τ : ℝ => (c₀ : ℝ) * τ) (c₀ : ℝ) s := by
        simpa using (hasDerivAt_id s).const_mul (c₀ : ℝ)
      simpa using h1.sub h2)
    t ht
  simp only [sol.init_μ, mul_zero, sub_zero] at h
  linarith

/-- α is explicitly exponential (uniqueness): `α t = exp (c₁ t)`. -/
theorem DynIteratorSol.alpha_eq {d : ℕ} {Fr : (Fin d → ℝ) → Fin d → ℝ}
    {A : ℚ} {L : ℕ} {c₀ c₁ : ℚ} {x₀ : Fin d → ℝ}
    (sol : DynIteratorSol d Fr A L c₀ c₁ x₀) :
    ∀ t : ℝ, 0 ≤ t → sol.α t = Real.exp ((c₁ : ℝ) * t) := by
  intro t ht
  have key := fwd_eq_of_deriv_zero
    (fun s => sol.α s * Real.exp (-((c₁ : ℝ) * s)))
    (fun s hs => by
      have h1 := sol.ode_α s hs
      have h2 : HasDerivAt (fun τ : ℝ => Real.exp (-((c₁ : ℝ) * τ)))
          (-(c₁ : ℝ) * Real.exp (-((c₁ : ℝ) * s))) s := by
        have hin : HasDerivAt (fun τ : ℝ => -((c₁ : ℝ) * τ)) (-(c₁ : ℝ)) s := by
          simpa using ((hasDerivAt_id s).const_mul (c₁ : ℝ)).neg
        have := hin.exp
        convert this using 1
        ring
      have h3 := h1.mul h2
      convert h3 using 1
      ring)
    t ht
  simp only [sol.init_α, mul_zero, neg_zero, Real.exp_zero, one_mul, mul_one] at key
  have hexp : Real.exp (-((c₁ : ℝ) * t)) > 0 := Real.exp_pos _
  have : sol.α t * Real.exp (-((c₁ : ℝ) * t)) = 1 := key
  have hgoal : sol.α t = (Real.exp (-((c₁ : ℝ) * t)))⁻¹ := by
    field_simp at this ⊢
    linarith [this]
  rw [hgoal, ← Real.exp_neg]
  ring_nf

/-! ## The dynamic cascade constants

Per cycle `C_j = [2πj, 2π(j+1)]`, using the monotone envelopes
`μ ∈ [c₀·2πj, c₀·2π(j+1)]` and `α ∈ [e^{c₁·2πj}, e^{c₁·2π(j+1)}]`. -/

/-- Contraction factor for cycle `j` (active-window estimate with the
worst-case envelope values). -/
noncomputable def dynKappa (A : ℝ) (L : ℕ) (c₀ c₁ : ℝ) (j : ℕ) : ℝ :=
  Real.exp (-(A * Real.exp (c₁ * 2*π*j)
    * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)))

/-- Per-cycle leak budget for cycle `j`, INTEGRAL form (the start-point
envelope is uselessly crude at small `j`; the integral
`∫_{2πj}^{2π(j+1)} α e^{−μ 2^{-L}} = ∫ e^{(c₁ − c₀ 2^{-L}) t}` collapses
within the cycle because μ grows linearly).  With the decay rate
`r := c₀ 2^{-L} − c₁ > 0` (parameter window):
`χ_j := e^{−r·2πj}/r ≥ ∫ over the cycle`.

Cascade verification (oracle, 2026-06-11): with the scaling
`c₀ = ε₀ 4^L` (ε₀ ≤ 1/(2π)) the active-window envelope gives
`κ_0 ≈ e^{−(2π/3) e^{−2πε₀}} < 1/2` already at cycle 0, κ_j strictly
decreasing (`c₁ > c₀ 4^{-L} = ε₀`), and `r = ε₀ 2^L − c₁ > (ln k)/2π`
has room for every `k` once `L` is large — all three V2/V3/V4
inequalities close. -/
noncomputable def dynChi (A : ℝ) (L : ℕ) (c₀ c₁ : ℝ) (j : ℕ) : ℝ :=
  A * Real.exp (-((c₀ * (1/2)^L - c₁) * (2*π*j))) / (c₀ * (1/2)^L - c₁)

private theorem dyn_phiZ_continuous (L : ℕ) (c₀ c₁ : ℝ) :
    Continuous fun t : ℝ => Real.exp (c₁ * t) * bGateZ L (c₀ * t) t := by
  unfold bGateZ rPulse
  fun_prop

private theorem dyn_phiU_continuous (L : ℕ) (c₀ c₁ : ℝ) :
    Continuous fun t : ℝ => Real.exp (c₁ * t) * bGateU L (c₀ * t) t := by
  unfold bGateU qPulse
  fun_prop

private theorem dyn_active_integral_lower_z
    (A : ℝ) (L : ℕ) (c₀ c₁ : ℝ) (j : ℕ)
    (hA : 0 ≤ A) (hc₀ : 0 ≤ c₀) (hc₁ : 0 ≤ c₁) :
    A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (2*π*j)..(2*π*j + π),
          A * (Real.exp (c₁ * t) * bGateZ L (c₀ * t) t) := by
  have hπ := Real.pi_pos
  set a : ℝ := 2 * π * (j:ℝ) with ha
  have h1 : a ≤ a + π/6 := by linarith
  have h2 : a + π/6 ≤ a + 5*π/6 := by linarith
  have h3 : a + 5*π/6 ≤ a + π := by linarith
  have ha_nonneg : 0 ≤ a := by dsimp [a]; positivity
  let φ : ℝ → ℝ := fun t => A * (Real.exp (c₁ * t) * bGateZ L (c₀ * t) t)
  have hφc : Continuous φ := by
    dsimp [φ]
    exact continuous_const.mul (dyn_phiZ_continuous L c₀ c₁)
  have hint : ∀ u v : ℝ, IntervalIntegrable φ MeasureTheory.volume u v :=
    fun u v => hφc.intervalIntegrable u v
  have e1 : (∫ t in a..(a+π/6), φ t)
      + (∫ t in (a+π/6)..(a+π), φ t)
      = ∫ t in a..(a+π), φ t :=
    intervalIntegral.integral_add_adjacent_intervals (hint _ _) (hint _ _)
  have e2 : (∫ t in (a+π/6)..(a+5*π/6), φ t)
      + (∫ t in (a+5*π/6)..(a+π), φ t)
      = ∫ t in (a+π/6)..(a+π), φ t :=
    intervalIntegral.integral_add_adjacent_intervals (hint _ _) (hint _ _)
  have hφ_nonneg : ∀ t, 0 ≤ φ t := by
    intro t
    dsimp [φ]
    exact mul_nonneg hA (mul_nonneg (Real.exp_pos _).le (bGateZ_pos L (c₀ * t) t).le)
  have hn1 : 0 ≤ ∫ t in a..(a+π/6), φ t :=
    intervalIntegral.integral_nonneg h1 (fun t _ => hφ_nonneg t)
  have hn3 : 0 ≤ ∫ t in (a+5*π/6)..(a+π), φ t :=
    intervalIntegral.integral_nonneg h3 (fun t _ => hφ_nonneg t)
  have hmid : A * Real.exp (c₁ * a)
        * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (a+π/6)..(a+5*π/6), φ t := by
    have hconst : (∫ _t in (a+π/6)..(a+5*π/6),
        A * Real.exp (c₁ * a)
          * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)))
        = A * Real.exp (c₁ * a)
          * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) * (2*π/3) := by
      rw [intervalIntegral.integral_const, smul_eq_mul]
      ring
    rw [← hconst]
    apply intervalIntegral.integral_mono_on h2 _root_.intervalIntegrable_const (hint _ _)
    intro t ht
    dsimp [φ]
    have hat : a ≤ t := le_trans h1 ht.1
    have htb : t ≤ a + 2*π := by nlinarith [hπ, ht.2]
    have hα : Real.exp (c₁ * a) ≤ Real.exp (c₁ * t) := by
      apply Real.exp_le_exp.mpr
      nlinarith
    have hgate : Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) ≤ bGateZ L (c₀ * t) t := by
      have hmt : c₀ * t ≤ c₀ * (a + 2*π) := mul_le_mul_of_nonneg_left htb hc₀
      have hs : (1:ℝ)/2 ≤ Real.sin t :=
        sin_window_ge j (by simpa [ha] using ht.1) (by simpa [ha] using ht.2)
      calc
        Real.exp (-(c₀ * (a + 2*π) * (1/4)^L))
            ≤ Real.exp (-(c₀ * t * (1/4)^L)) := by
              apply Real.exp_le_exp.mpr
              have hp : 0 ≤ ((1:ℝ)/4)^L := pow_nonneg (by norm_num) L
              nlinarith
        _ ≤ bGateZ L (c₀ * t) t :=
              bGateZ_ge_active L (mul_nonneg hc₀ (le_trans ha_nonneg hat)) hs
    have hmul := mul_le_mul hα hgate (Real.exp_pos _).le (Real.exp_pos _).le
    have hA_mul := mul_le_mul_of_nonneg_left hmul hA
    simpa [mul_assoc] using hA_mul
  have hgoal_mid :
      A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (a+π/6)..(a+5*π/6), φ t := by
    simpa [ha, Nat.cast_add, left_distrib, add_comm, add_left_comm, add_assoc,
      mul_add, add_mul, mul_assoc] using hmid
  have hfull :
      A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in a..(a+π), φ t := by
    linarith [e1, e2, hn1, hn3, hgoal_mid]
  simpa [φ, ha] using hfull

private theorem dyn_active_integral_lower_u
    (A : ℝ) (L : ℕ) (c₀ c₁ : ℝ) (j : ℕ)
    (hA : 0 ≤ A) (hc₀ : 0 ≤ c₀) (hc₁ : 0 ≤ c₁) :
    A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (2*π*j + π)..(2*π*j + 2*π),
          A * (Real.exp (c₁ * t) * bGateU L (c₀ * t) t) := by
  have hπ := Real.pi_pos
  set a : ℝ := 2 * π * (j:ℝ) with ha
  have h1 : a + π ≤ a + 7*π/6 := by linarith
  have h2 : a + 7*π/6 ≤ a + 11*π/6 := by linarith
  have h3 : a + 11*π/6 ≤ a + 2*π := by linarith
  have ha_nonneg : 0 ≤ a := by dsimp [a]; positivity
  let φ : ℝ → ℝ := fun t => A * (Real.exp (c₁ * t) * bGateU L (c₀ * t) t)
  have hφc : Continuous φ := by
    dsimp [φ]
    exact continuous_const.mul (dyn_phiU_continuous L c₀ c₁)
  have hint : ∀ u v : ℝ, IntervalIntegrable φ MeasureTheory.volume u v :=
    fun u v => hφc.intervalIntegrable u v
  have e1 : (∫ t in (a+π)..(a+7*π/6), φ t)
      + (∫ t in (a+7*π/6)..(a+2*π), φ t)
      = ∫ t in (a+π)..(a+2*π), φ t :=
    intervalIntegral.integral_add_adjacent_intervals (hint _ _) (hint _ _)
  have e2 : (∫ t in (a+7*π/6)..(a+11*π/6), φ t)
      + (∫ t in (a+11*π/6)..(a+2*π), φ t)
      = ∫ t in (a+7*π/6)..(a+2*π), φ t :=
    intervalIntegral.integral_add_adjacent_intervals (hint _ _) (hint _ _)
  have hφ_nonneg : ∀ t, 0 ≤ φ t := by
    intro t
    dsimp [φ]
    exact mul_nonneg hA (mul_nonneg (Real.exp_pos _).le (bGateU_pos L (c₀ * t) t).le)
  have hn1 : 0 ≤ ∫ t in (a+π)..(a+7*π/6), φ t :=
    intervalIntegral.integral_nonneg h1 (fun t _ => hφ_nonneg t)
  have hn3 : 0 ≤ ∫ t in (a+11*π/6)..(a+2*π), φ t :=
    intervalIntegral.integral_nonneg h3 (fun t _ => hφ_nonneg t)
  have hmid : A * Real.exp (c₁ * a)
        * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (a+7*π/6)..(a+11*π/6), φ t := by
    have hconst : (∫ _t in (a+7*π/6)..(a+11*π/6),
        A * Real.exp (c₁ * a)
          * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)))
        = A * Real.exp (c₁ * a)
          * Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) * (2*π/3) := by
      rw [intervalIntegral.integral_const, smul_eq_mul]
      ring
    rw [← hconst]
    apply intervalIntegral.integral_mono_on h2 _root_.intervalIntegrable_const (hint _ _)
    intro t ht
    dsimp [φ]
    have hat : a ≤ t := by nlinarith [hπ, ht.1]
    have htb : t ≤ a + 2*π := by nlinarith [hπ, ht.2]
    have hα : Real.exp (c₁ * a) ≤ Real.exp (c₁ * t) := by
      apply Real.exp_le_exp.mpr
      nlinarith
    have hgate : Real.exp (-(c₀ * (a + 2*π) * (1/4)^L)) ≤ bGateU L (c₀ * t) t := by
      have hmt : c₀ * t ≤ c₀ * (a + 2*π) := mul_le_mul_of_nonneg_left htb hc₀
      have hs : Real.sin t ≤ -(1/2) :=
        sin_window_le_neg_half j (by simpa [ha] using ht.1) (by simpa [ha] using ht.2)
      calc
        Real.exp (-(c₀ * (a + 2*π) * (1/4)^L))
            ≤ Real.exp (-(c₀ * t * (1/4)^L)) := by
              apply Real.exp_le_exp.mpr
              have hp : 0 ≤ ((1:ℝ)/4)^L := pow_nonneg (by norm_num) L
              nlinarith
        _ ≤ bGateU L (c₀ * t) t :=
              bGateU_ge_active L (mul_nonneg hc₀ (le_trans ha_nonneg hat)) hs
    have hmul := mul_le_mul hα hgate (Real.exp_pos _).le (Real.exp_pos _).le
    have hA_mul := mul_le_mul_of_nonneg_left hmul hA
    simpa [mul_assoc] using hA_mul
  have hgoal_mid :
      A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (a+7*π/6)..(a+11*π/6), φ t := by
    simpa [ha, Nat.cast_add, left_distrib, add_comm, add_left_comm, add_assoc,
      mul_add, add_mul, mul_assoc] using hmid
  have hfull :
      A * Real.exp (c₁ * (2*π*j))
        * Real.exp (-(c₀ * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
      ≤ ∫ t in (a+π)..(a+2*π), φ t := by
    linarith [e1, e2, hn1, hn3, hgoal_mid]
  simpa [φ, ha] using hfull

private theorem exp_decay_cycle_integral_le
    (A lam a b : ℝ) (hA : 0 ≤ A) (hlam : 0 < lam) (hab : a ≤ b) :
    ∫ t in a..b, A * Real.exp (-(lam * t)) ≤ A * Real.exp (-(lam * a)) / lam := by
  have hcont : Continuous fun t : ℝ => A * Real.exp (-(lam * t)) := by fun_prop
  have hderiv : ∀ t : ℝ,
      HasDerivAt (fun s : ℝ => -(A / lam) * Real.exp (-(lam * s)))
        (A * Real.exp (-(lam * t))) t := by
    intro t
    have hin : HasDerivAt (fun s : ℝ => -(lam * s)) (-lam) t := by
      simpa using ((hasDerivAt_id t).const_mul lam).neg
    have h := hin.exp.const_mul (-(A / lam))
    convert h using 1
    field_simp [ne_of_gt hlam]
  have hftc :
      (∫ t in a..b, A * Real.exp (-(lam * t)))
        = (-(A / lam) * Real.exp (-(lam * b)))
          - (-(A / lam) * Real.exp (-(lam * a))) := by
    apply intervalIntegral.integral_eq_sub_of_hasDerivAt
    · intro t _
      exact hderiv t
    · exact hcont.intervalIntegrable a b
  rw [hftc]
  have hterm_nonneg : 0 ≤ (A / lam) * Real.exp (-(lam * b)) := by positivity
  calc
    -(A / lam) * Real.exp (-(lam * b)) - (-(A / lam) * Real.exp (-(lam * a)))
        = A * Real.exp (-(lam * a)) / lam - (A / lam) * Real.exp (-(lam * b)) := by ring
    _ ≤ A * Real.exp (-(lam * a)) / lam := by linarith

/-! ## v2 obligations (V1–V4) -/

set_option maxHeartbeats 800000

/-- **V1, dynamic perturbation recurrence**: one cycle of the dynamic
iterator maps sampling error `e` to
`≤ 2 dynKappa_j (e + D_K) + 2 dynChi_j D_K + ηstep`, under the moving
box and the snap-basin condition — the j-dependent analog of P4,
assembled from `targeting_bound`/`hold_bound` with `φ := α·bGate` and
the gate-value bounds above.  (Constants adjustable as long as V2
closes.) -/
theorem dyn_perturbation_recurrence
    {Conf : Type} [Primcodable Conf]
    (Mch : DiscreteMachine Conf) (d : ℕ) (E : LatticeEncoding Mch d)
    (S : RobustRealExtension Mch d E)
    (A : ℚ) (hA : 0 < A)
    (L : ℕ) (c₀ c₁ : ℚ) (hc₀ : 0 < c₀) (hc₁ : 0 < c₁)
    (hlam : 0 < (c₀ : ℝ) * (1/2)^L - (c₁ : ℝ)) (w : ℕ)
    (sol : DynIteratorSol d S.evalF A L c₀ c₁ (orbitPoint Mch E w 0))
    (D_K : ℝ) (hD : 0 < D_K)
    (hbox : ∀ (j : ℕ) (t : ℝ), t ∈ Set.Icc (2*π*j) (2*π*(j+1)) →
      (∀ i, |orbitPoint Mch E w (j+1) i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |sol.z t i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |sol.u t i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |S.evalF (sol.u t) i - orbitPoint Mch E w j i| ≤ D_K))
    (j : ℕ) (e : ℝ) (he0 : 0 ≤ e)
    (he : ∀ i, |sol.z (2*π*j) i - orbitPoint Mch E w j i| ≤ e ∧
               |sol.u (2*π*j) i - orbitPoint Mch E w j i| ≤ e)
    (hsnap : e + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K ≤ (S.r₀ : ℝ)) :
    ∀ i, |sol.z (2*π*(j+1)) i - orbitPoint Mch E w (j+1) i| ≤
          2 * dynKappa (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * (e + D_K)
            + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K + (S.ηstep : ℝ) ∧
         |sol.u (2*π*(j+1)) i - orbitPoint Mch E w (j+1) i| ≤
          2 * dynKappa (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * (e + D_K)
            + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K + (S.ηstep : ℝ) := by
  intro i
  let AR : ℝ := (A : ℝ)
  let c0R : ℝ := (c₀ : ℝ)
  let c1R : ℝ := (c₁ : ℝ)
  let lam : ℝ := c0R * (1/2)^L - c1R
  let a : ℝ := 2 * π * (j : ℝ)
  let m : ℝ := 2 * π * (j : ℝ) + π
  let b : ℝ := 2 * π * (j : ℝ) + 2 * π
  let xj : Fin d → ℝ := orbitPoint Mch E w j
  let xnext : Fin d → ℝ := orbitPoint Mch E w (j + 1)
  let leak : ℝ → ℝ := fun t => AR * Real.exp (-(lam * t))
  let I1 : ℝ := ∫ t in a..m, leak t
  let I2 : ℝ := ∫ t in m..b, leak t
  let H1 : ℝ := 2 * D_K * I1
  let H2 : ℝ := 2 * D_K * I2
  have hπ : 0 < π := Real.pi_pos
  have hAℝ : 0 < AR := by dsimp [AR]; exact_mod_cast hA
  have hA_nonneg : 0 ≤ AR := hAℝ.le
  have hc0ℝ : 0 < c0R := by dsimp [c0R]; exact_mod_cast hc₀
  have hc1ℝ : 0 < c1R := by dsimp [c1R]; exact_mod_cast hc₁
  have hc0_nonneg : 0 ≤ c0R := hc0ℝ.le
  have hc1_nonneg : 0 ≤ c1R := hc1ℝ.le
  have hlamR : 0 < lam := by simpa [lam, c0R, c1R] using hlam
  have ha0 : (0:ℝ) ≤ a :=
    mul_nonneg (mul_nonneg (by norm_num) Real.pi_pos.le) (Nat.cast_nonneg j)
  have hamb : a ≤ m := by dsimp [a, m]; linarith
  have hmb : m ≤ b := by dsimp [m, b]; linarith [hπ]
  have hab : a ≤ b := le_trans hamb hmb
  have hb_eq : b = 2 * π * ((j : ℝ) + 1) := by dsimp [b]; ring
  have ha_eq : a = 2 * π * j := rfl
  have hm_eq : m = 2 * π * j + π := rfl
  have hcycle_m : m ∈ Set.Icc (2*π*j) (2*π*(j+1)) := by
    constructor
    · simpa [a, m] using hamb
    · simpa [← hb_eq] using hmb
  have hxnext_box : ∀ k, |xnext k - xj k| ≤ D_K := (hbox j m hcycle_m).1
  have hz_cont : ∀ k, Continuous fun t => sol.z t k := fun k => sol.cont_z k
  have hu_cont : ∀ k, Continuous fun t => sol.u t k := fun k => sol.cont_u k
  have hEval_cont : ∀ k, Continuous fun t => S.evalF (sol.u t) k := fun k => by
    have hsolu : Continuous fun t => sol.u t := continuous_pi fun l => hu_cont l
    unfold RobustRealExtension.evalF
    convert
      (MvPolynomial.continuous_eval (p := MvPolynomial.map (algebraMap ℚ ℝ) (S.F k))).comp hsolu
      using 1
    ext t
    exact MvPolynomial.eval₂_eq_eval_map (algebraMap ℚ ℝ) (sol.u t) (S.F k)
  have hD_nonneg : 0 ≤ D_K := hD.le
  have hη_nonneg : 0 ≤ (S.ηstep : ℝ) := by exact_mod_cast S.ηstep_pos.le
  have hκ_nonneg : 0 ≤ dynKappa AR L c0R c1R j := by
    unfold dynKappa
    exact (Real.exp_pos _).le
  have hκ_le_one : dynKappa AR L c0R c1R j ≤ 1 := by
    unfold dynKappa
    apply Real.exp_le_one_iff.mpr
    have : 0 ≤ AR * Real.exp (c1R * 2*π*j)
        * Real.exp (-(c0R * 2*π*(j+1) * (1/4)^L)) * (2*π/3) := by
      positivity
    nlinarith
  have hχ_nonneg : 0 ≤ dynChi AR L c0R c1R j := by
    unfold dynChi
    positivity
  have hleak_cont : Continuous leak := by
    dsimp [leak]
    fun_prop
  have hleak_nonneg : ∀ t, 0 ≤ leak t := by
    intro t
    dsimp [leak]
    positivity
  have hI1_nonneg : 0 ≤ I1 := by
    dsimp [I1]
    exact intervalIntegral.integral_nonneg hamb (fun t _ => hleak_nonneg t)
  have hI2_nonneg : 0 ≤ I2 := by
    dsimp [I2]
    exact intervalIntegral.integral_nonneg hmb (fun t _ => hleak_nonneg t)
  have hH1_nonneg : 0 ≤ H1 := by dsimp [H1]; positivity
  have hH2_nonneg : 0 ≤ H2 := by dsimp [H2]; positivity
  have hI_sum_le : I1 + I2 ≤ dynChi AR L c0R c1R j := by
    have hadd : I1 + I2 = ∫ t in a..b, leak t := by
      dsimp [I1, I2]
      exact intervalIntegral.integral_add_adjacent_intervals
        (hleak_cont.intervalIntegrable a m) (hleak_cont.intervalIntegrable m b)
    have hcyc : (∫ t in a..b, leak t) ≤ dynChi AR L c0R c1R j := by
      have h := exp_decay_cycle_integral_le AR lam a b hA_nonneg hlamR hab
      simpa [leak, dynChi, lam, a, AR, c0R, c1R, mul_assoc] using h
    linarith
  have hH_sum_le : H1 + H2 ≤ 2 * dynChi AR L c0R c1R j * D_K := by
    dsimp [H1, H2]
    nlinarith [hI_sum_le, hD_nonneg]
  have hold_u_first :
      ∀ t ∈ Set.Icc a m, ∀ k, |sol.u t k - sol.u a k| ≤ H1 := by
    intro t ht k
    have hat : a ≤ t := ht.1
    have htm : t ≤ m := ht.2
    let g : ℝ → ℝ := fun s =>
      AR * (Real.exp (c1R * s) * bGateU L (c0R * s) s) * (sol.z s k - sol.u s k)
    have hg_cont : Continuous g := by
      dsimp [g]
      have hzu : Continuous fun s => sol.z s k - sol.u s k := (hz_cont k).sub (hu_cont k)
      exact (continuous_const.mul (dyn_phiU_continuous L c0R c1R)).mul hzu
    have hderiv : ∀ s ∈ Set.Icc a t, HasDerivAt (fun τ => sol.u τ k) (g s) s := by
      intro s hs
      have hs0 : 0 ≤ s := le_trans ha0 hs.1
      have hα := sol.alpha_eq s hs0
      have hμ := sol.mu_eq s hs0
      have hode := sol.ode_u s hs0 k
      dsimp [g, AR, c0R, c1R]
      convert hode using 1 <;> simp [hα, hμ, mul_assoc]
    have hhold := hold_bound_integral (fun τ => sol.u τ k) g a t hat hg_cont hderiv
    have hint_le : (∫ s in a..t, |g s|) ≤ ∫ s in a..t, 2 * D_K * leak s := by
      apply intervalIntegral.integral_mono_on hat
      · exact hg_cont.abs.intervalIntegrable a t
      · exact (continuous_const.mul hleak_cont).intervalIntegrable a t
      intro s hs
      have hs0 : 0 ≤ s := le_trans ha0 hs.1
      have hs_cycle : s ∈ Set.Icc (2*π*j) (2*π*(j+1)) := by
        simpa [a, ← hb_eq] using
          (⟨hs.1, le_trans hs.2 (le_trans htm hmb)⟩ : s ∈ Set.Icc a b)
      have hzD := (hbox j s hs_cycle).2.1 k
      have huD := (hbox j s hs_cycle).2.2.1 k
      have hzu : |sol.z s k - sol.u s k| ≤ 2 * D_K := by
        calc
          |sol.z s k - sol.u s k|
              = |(sol.z s k - xj k) - (sol.u s k - xj k)| := by ring_nf
          _ ≤ |sol.z s k - xj k| + |sol.u s k - xj k| := by
            simpa [abs_sub_comm] using abs_sub_le (sol.z s k) (xj k) (sol.u s k)
          _ ≤ D_K + D_K := add_le_add hzD huD
          _ = 2 * D_K := by ring
      have hgate : bGateU L (c0R * s) s ≤ Real.exp (-(c0R * s * (1/2)^L)) := by
        have hsin : 0 ≤ Real.sin s := by
          apply sin_window_nonneg j
          · simpa [a] using hs_cycle.1
          · have : s ≤ 2 * π * j + π := by rw [← hm_eq]; exact le_trans hs.2 htm
            simpa using this
        exact bGateU_le_offphase L (mul_nonneg hc0_nonneg hs0) hsin
      have hprof_le : AR * (Real.exp (c1R * s) * bGateU L (c0R * s) s) ≤ leak s := by
        dsimp [leak]
        have hexp_nonneg : 0 ≤ Real.exp (c1R * s) := (Real.exp_pos _).le
        have hgate_mul :
            Real.exp (c1R * s) * bGateU L (c0R * s) s
              ≤ Real.exp (c1R * s) * Real.exp (-(c0R * s * (1/2)^L)) :=
          mul_le_mul_of_nonneg_left hgate hexp_nonneg
        have hmul := mul_le_mul_of_nonneg_left hgate_mul hA_nonneg
        calc
          AR * (Real.exp (c1R * s) * bGateU L (c0R * s) s)
              ≤ AR * (Real.exp (c1R * s) * Real.exp (-(c0R * s * (1/2)^L))) := hmul
          _ = AR * Real.exp (-(lam * s)) := by
                congr 1
                rw [← Real.exp_add]
                congr 1
                dsimp [lam]
                ring
      have hprof_nonneg : 0 ≤ AR * (Real.exp (c1R * s) * bGateU L (c0R * s) s) := by
        exact mul_nonneg hA_nonneg
          (mul_nonneg (Real.exp_pos _).le (bGateU_pos L (c0R * s) s).le)
      calc
        |g s| = AR * (Real.exp (c1R * s) * bGateU L (c0R * s) s) *
            |sol.z s k - sol.u s k| := by
          dsimp [g]
          rw [abs_mul, abs_of_nonneg hprof_nonneg]
        _ ≤ leak s * (2 * D_K) := mul_le_mul hprof_le hzu (abs_nonneg _) (hleak_nonneg s)
        _ = 2 * D_K * leak s := by ring
    have hIt_le : (∫ s in a..t, leak s) ≤ I1 := by
      have htail_nonneg : 0 ≤ ∫ s in t..m, leak s :=
        intervalIntegral.integral_nonneg htm (fun s _ => hleak_nonneg s)
      have hadd : (∫ s in a..t, leak s) + (∫ s in t..m, leak s) = I1 := by
        dsimp [I1]
        exact intervalIntegral.integral_add_adjacent_intervals
          (hleak_cont.intervalIntegrable a t) (hleak_cont.intervalIntegrable t m)
      linarith
    calc
      |sol.u t k - sol.u a k| ≤ ∫ s in a..t, |g s| := hhold
      _ ≤ ∫ s in a..t, 2 * D_K * leak s := hint_le
      _ = 2 * D_K * (∫ s in a..t, leak s) := by
            rw [intervalIntegral.integral_const_mul]
      _ ≤ H1 := by
            dsimp [H1]
            exact mul_le_mul_of_nonneg_left hIt_le (by positivity)
  have hu_first_near : ∀ t ∈ Set.Icc a m, ∀ k, |sol.u t k - xj k| ≤ e + H1 := by
    intro t ht k
    have hstart := (he k).2
    rw [← ha_eq] at hstart
    have hhold := hold_u_first t ht k
    calc
      |sol.u t k - xj k|
          = |(sol.u t k - sol.u a k) + (sol.u a k - xj k)| := by ring_nf
      _ ≤ |sol.u t k - sol.u a k| + |sol.u a k - xj k| := abs_add_le _ _
      _ ≤ H1 + e := add_le_add hhold hstart
      _ = e + H1 := by ring
  have hH1_le : H1 ≤ 2 * dynChi AR L c0R c1R j * D_K := by
    nlinarith [hH_sum_le, hH2_nonneg]
  have hsnap_first : ∀ t ∈ Set.Icc a m, ∀ k, |S.evalF (sol.u t) k - xnext k| ≤ (S.ηstep : ℝ) := by
    intro t ht k
    have hnear : ∀ l, |sol.u t l - E.enc (Mch.step^[j] (Mch.init w)) l| ≤ (S.r₀ : ℝ) := by
      intro l
      exact le_trans (hu_first_near t ht l) (by nlinarith [hsnap, hH1_le])
    simpa [RobustRealExtension.evalF, orbitPoint, xnext, Function.iterate_succ_apply'] using
      S.snap (Mch.step^[j] (Mch.init w)) (sol.u t) hnear k
  have target_z (k : Fin d) :
      |sol.z m k - xnext k| ≤ dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) := by
    let φz : ℝ → ℝ := fun t => Real.exp (c1R * t) * bGateZ L (c0R * t) t
    have hδ : ∀ t ∈ Set.Icc a m, |S.evalF (sol.u t) k - xnext k| ≤ (S.ηstep : ℝ) :=
      fun t ht => hsnap_first t ht k
    have hderiv : ∀ t ∈ Set.Icc a m,
        HasDerivAt (fun τ => sol.z τ k) (AR * φz t * (S.evalF (sol.u t) k - sol.z t k)) t := by
      intro t ht
      have ht0 : 0 ≤ t := le_trans ha0 ht.1
      have hα := sol.alpha_eq t ht0
      have hμ := sol.mu_eq t ht0
      have hode := sol.ode_z t ht0 k
      dsimp [φz, AR, c0R, c1R]
      convert hode using 1 <;> simp [hα, hμ, mul_assoc]
    have htarget := targeting_bound AR hAℝ φz
      (fun t => S.evalF (sol.u t) k) (fun t => sol.z t k) a m hamb
      (dyn_phiZ_continuous L c0R c1R)
      (fun t ht => by
        dsimp [φz]
        exact mul_nonneg (Real.exp_pos _).le (bGateZ_pos L (c0R * t) t).le)
      (hEval_cont k) (xnext k) (S.ηstep : ℝ) hδ hderiv
    have hInt : AR * Real.exp (c1R * (2*π*j))
          * Real.exp (-(c0R * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
        ≤ AR * ∫ t in a..m, φz t := by
      simpa [φz, a, m, AR, c0R, c1R] using
        dyn_active_integral_lower_z AR L c0R c1R j hA_nonneg hc0_nonneg hc1_nonneg
    have hcoef :
        Real.exp (-(AR * ∫ t in a..m, φz t)) ≤ dynKappa AR L c0R c1R j := by
      unfold dynKappa
      have hInt' :
          AR * Real.exp (c1R * 2*π*j)
              * Real.exp (-(c0R * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
            ≤ AR * ∫ t in a..m, φz t := by
        simpa [mul_assoc] using hInt
      exact Real.exp_le_exp.mpr (neg_le_neg hInt')
    have hstartz := (he k).1
    rw [← ha_eq] at hstartz
    have hxgap := hxnext_box k
    have hza : |sol.z a k - xnext k| ≤ e + D_K := by
      calc
        |sol.z a k - xnext k|
            = |(sol.z a k - xj k) - (xnext k - xj k)| := by ring_nf
        _ ≤ |sol.z a k - xj k| + |xnext k - xj k| := by
          simpa [abs_sub_comm] using abs_sub_le (sol.z a k) (xj k) (xnext k)
        _ ≤ e + D_K := add_le_add hstartz hxgap
    have hmul :
        Real.exp (-(AR * ∫ t in a..m, φz t)) * |sol.z a k - xnext k|
          ≤ dynKappa AR L c0R c1R j * (e + D_K) := by
      exact mul_le_mul hcoef hza (abs_nonneg _) hκ_nonneg
    exact le_trans htarget (by
      simpa [add_comm, add_left_comm, add_assoc] using
        add_le_add_right hmul (S.ηstep : ℝ))
  have hold_z_second :
      ∀ t ∈ Set.Icc m b, ∀ k, |sol.z t k - sol.z m k| ≤ H2 := by
    intro t ht k
    have hmt : m ≤ t := ht.1
    have htb : t ≤ b := ht.2
    let g : ℝ → ℝ := fun s =>
      AR * (Real.exp (c1R * s) * bGateZ L (c0R * s) s) * (S.evalF (sol.u s) k - sol.z s k)
    have hg_cont : Continuous g := by
      dsimp [g]
      have hFz : Continuous fun s => S.evalF (sol.u s) k - sol.z s k :=
        (hEval_cont k).sub (hz_cont k)
      exact (continuous_const.mul (dyn_phiZ_continuous L c0R c1R)).mul hFz
    have hderiv : ∀ s ∈ Set.Icc m t, HasDerivAt (fun τ => sol.z τ k) (g s) s := by
      intro s hs
      have hs0 : 0 ≤ s := le_trans (le_trans ha0 hamb) hs.1
      have hα := sol.alpha_eq s hs0
      have hμ := sol.mu_eq s hs0
      have hode := sol.ode_z s hs0 k
      dsimp [g, AR, c0R, c1R]
      convert hode using 1 <;> simp [hα, hμ, mul_assoc]
    have hhold := hold_bound_integral (fun τ => sol.z τ k) g m t hmt hg_cont hderiv
    have hint_le : (∫ s in m..t, |g s|) ≤ ∫ s in m..t, 2 * D_K * leak s := by
      apply intervalIntegral.integral_mono_on hmt
      · exact hg_cont.abs.intervalIntegrable m t
      · exact (continuous_const.mul hleak_cont).intervalIntegrable m t
      intro s hs
      have hs0 : 0 ≤ s := le_trans (le_trans ha0 hamb) hs.1
      have hs_cycle : s ∈ Set.Icc (2*π*j) (2*π*(j+1)) := by
        simpa [a, ← hb_eq] using
          (⟨le_trans hamb hs.1, le_trans hs.2 htb⟩ : s ∈ Set.Icc a b)
      have hFD := (hbox j s hs_cycle).2.2.2 k
      have hzD := (hbox j s hs_cycle).2.1 k
      have hFz : |S.evalF (sol.u s) k - sol.z s k| ≤ 2 * D_K := by
        calc
          |S.evalF (sol.u s) k - sol.z s k|
              = |(S.evalF (sol.u s) k - xj k) - (sol.z s k - xj k)| := by ring_nf
          _ ≤ |S.evalF (sol.u s) k - xj k| + |sol.z s k - xj k| := by
            simpa [abs_sub_comm] using abs_sub_le (S.evalF (sol.u s) k) (xj k) (sol.z s k)
          _ ≤ D_K + D_K := add_le_add hFD hzD
          _ = 2 * D_K := by ring
      have hgate : bGateZ L (c0R * s) s ≤ Real.exp (-(c0R * s * (1/2)^L)) := by
        have hsin : Real.sin s ≤ 0 := by
          apply sin_window_nonpos j
          · have : 2 * π * j + π ≤ s := by rw [← hm_eq]; exact hs.1
            simpa using this
          · simpa [← hb_eq] using hs_cycle.2
        exact bGateZ_le_offphase L (mul_nonneg hc0_nonneg hs0) hsin
      have hprof_le : AR * (Real.exp (c1R * s) * bGateZ L (c0R * s) s) ≤ leak s := by
        dsimp [leak]
        have hexp_nonneg : 0 ≤ Real.exp (c1R * s) := (Real.exp_pos _).le
        have hgate_mul :
            Real.exp (c1R * s) * bGateZ L (c0R * s) s
              ≤ Real.exp (c1R * s) * Real.exp (-(c0R * s * (1/2)^L)) :=
          mul_le_mul_of_nonneg_left hgate hexp_nonneg
        have hmul := mul_le_mul_of_nonneg_left hgate_mul hA_nonneg
        calc
          AR * (Real.exp (c1R * s) * bGateZ L (c0R * s) s)
              ≤ AR * (Real.exp (c1R * s) * Real.exp (-(c0R * s * (1/2)^L))) := hmul
          _ = AR * Real.exp (-(lam * s)) := by
                congr 1
                rw [← Real.exp_add]
                congr 1
                dsimp [lam]
                ring
      have hprof_nonneg : 0 ≤ AR * (Real.exp (c1R * s) * bGateZ L (c0R * s) s) := by
        exact mul_nonneg hA_nonneg
          (mul_nonneg (Real.exp_pos _).le (bGateZ_pos L (c0R * s) s).le)
      calc
        |g s| = AR * (Real.exp (c1R * s) * bGateZ L (c0R * s) s) *
            |S.evalF (sol.u s) k - sol.z s k| := by
          dsimp [g]
          rw [abs_mul, abs_of_nonneg hprof_nonneg]
        _ ≤ leak s * (2 * D_K) := mul_le_mul hprof_le hFz (abs_nonneg _) (hleak_nonneg s)
        _ = 2 * D_K * leak s := by ring
    have hIt_le : (∫ s in m..t, leak s) ≤ I2 := by
      have htail_nonneg : 0 ≤ ∫ s in t..b, leak s :=
        intervalIntegral.integral_nonneg htb (fun s _ => hleak_nonneg s)
      have hadd : (∫ s in m..t, leak s) + (∫ s in t..b, leak s) = I2 := by
        dsimp [I2]
        exact intervalIntegral.integral_add_adjacent_intervals
          (hleak_cont.intervalIntegrable m t) (hleak_cont.intervalIntegrable t b)
      linarith
    calc
      |sol.z t k - sol.z m k| ≤ ∫ s in m..t, |g s| := hhold
      _ ≤ ∫ s in m..t, 2 * D_K * leak s := hint_le
      _ = 2 * D_K * (∫ s in m..t, leak s) := by
            rw [intervalIntegral.integral_const_mul]
      _ ≤ H2 := by
            dsimp [H2]
            exact mul_le_mul_of_nonneg_left hIt_le (by positivity)
  have hz_second_near : ∀ t ∈ Set.Icc m b, ∀ k,
      |sol.z t k - xnext k| ≤
        dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2 := by
    intro t ht k
    have hmidk := target_z k
    have hhold := hold_z_second t ht k
    calc
      |sol.z t k - xnext k|
          = |(sol.z t k - sol.z m k) + (sol.z m k - xnext k)| := by ring_nf
      _ ≤ |sol.z t k - sol.z m k| + |sol.z m k - xnext k| := abs_add_le _ _
      _ ≤ H2 + (dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ)) :=
            add_le_add hhold hmidk
      _ = dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2 := by ring
  have hz_b_pre :
      |sol.z b i - xnext i| ≤
        dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2 :=
    hz_second_near b (Set.right_mem_Icc.mpr hmb) i
  have hu_m_xnext : ∀ k, |sol.u m k - xnext k| ≤ e + H1 + D_K := by
    intro k
    have hu_near := hu_first_near m (Set.right_mem_Icc.mpr hamb) k
    have hxgap := hxnext_box k
    calc
      |sol.u m k - xnext k|
          = |(sol.u m k - xj k) - (xnext k - xj k)| := by ring_nf
      _ ≤ |sol.u m k - xj k| + |xnext k - xj k| := by
        simpa [abs_sub_comm] using abs_sub_le (sol.u m k) (xj k) (xnext k)
      _ ≤ (e + H1) + D_K := add_le_add hu_near hxgap
      _ = e + H1 + D_K := by ring
  have hu_b_pre :
      |sol.u b i - xnext i| ≤
        dynKappa AR L c0R c1R j * (e + H1 + D_K) +
          (dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2) := by
    let φu : ℝ → ℝ := fun t => Real.exp (c1R * t) * bGateU L (c0R * t) t
    have hδ : ∀ t ∈ Set.Icc m b,
        |sol.z t i - xnext i| ≤
          dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2 :=
      fun t ht => hz_second_near t ht i
    have hderiv : ∀ t ∈ Set.Icc m b,
        HasDerivAt (fun τ => sol.u τ i) (AR * φu t * (sol.z t i - sol.u t i)) t := by
      intro t ht
      have ht0 : 0 ≤ t := le_trans (le_trans ha0 hamb) ht.1
      have hα := sol.alpha_eq t ht0
      have hμ := sol.mu_eq t ht0
      have hode := sol.ode_u t ht0 i
      dsimp [φu, AR, c0R, c1R]
      convert hode using 1 <;> simp [hα, hμ, mul_assoc]
    have htarget := targeting_bound AR hAℝ φu
      (fun t => sol.z t i) (fun t => sol.u t i) m b hmb
      (dyn_phiU_continuous L c0R c1R)
      (fun t ht => by
        dsimp [φu]
        exact mul_nonneg (Real.exp_pos _).le (bGateU_pos L (c0R * t) t).le)
      (hz_cont i) (xnext i)
      (dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2)
      hδ hderiv
    have hInt : AR * Real.exp (c1R * (2*π*j))
          * Real.exp (-(c0R * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
        ≤ AR * ∫ t in m..b, φu t := by
      simpa [φu, m, b, AR, c0R, c1R] using
        dyn_active_integral_lower_u AR L c0R c1R j hA_nonneg hc0_nonneg hc1_nonneg
    have hcoef :
        Real.exp (-(AR * ∫ t in m..b, φu t)) ≤ dynKappa AR L c0R c1R j := by
      unfold dynKappa
      have hInt' :
          AR * Real.exp (c1R * 2*π*j)
              * Real.exp (-(c0R * 2*π*(j+1) * (1/4)^L)) * (2*π/3)
            ≤ AR * ∫ t in m..b, φu t := by
        simpa [mul_assoc] using hInt
      exact Real.exp_le_exp.mpr (neg_le_neg hInt')
    have hmul :
        Real.exp (-(AR * ∫ t in m..b, φu t)) * |sol.u m i - xnext i|
          ≤ dynKappa AR L c0R c1R j * (e + H1 + D_K) := by
      exact mul_le_mul hcoef (hu_m_xnext i) (abs_nonneg _) hκ_nonneg
    exact le_trans htarget (by
      simpa [add_comm, add_left_comm, add_assoc] using
        add_le_add_right hmul
          (dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2))
  constructor
  · change |sol.z (2 * π * ((j : ℝ) + 1)) i - xnext i| ≤
      2 * dynKappa AR L c0R c1R j * (e + D_K)
        + 2 * dynChi AR L c0R c1R j * D_K + (S.ηstep : ℝ)
    have hb' : 2 * π * ((j : ℝ) + 1) = b := by dsimp [b]; ring
    rw [hb']
    calc
      |sol.z b i - xnext i|
          ≤ dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2 := hz_b_pre
      _ ≤ 2 * dynKappa AR L c0R c1R j * (e + D_K)
          + 2 * dynChi AR L c0R c1R j * D_K + (S.ηstep : ℝ) := by
            nlinarith [hκ_nonneg, he0, hD_nonneg, hH_sum_le, hH1_nonneg]
  · change |sol.u (2 * π * ((j : ℝ) + 1)) i - xnext i| ≤
      2 * dynKappa AR L c0R c1R j * (e + D_K)
        + 2 * dynChi AR L c0R c1R j * D_K + (S.ηstep : ℝ)
    have hb' : 2 * π * ((j : ℝ) + 1) = b := by dsimp [b]; ring
    rw [hb']
    calc
      |sol.u b i - xnext i|
          ≤ dynKappa AR L c0R c1R j * (e + H1 + D_K) +
            (dynKappa AR L c0R c1R j * (e + D_K) + (S.ηstep : ℝ) + H2) := hu_b_pre
      _ ≤ 2 * dynKappa AR L c0R c1R j * (e + D_K)
          + 2 * dynChi AR L c0R c1R j * D_K + (S.ηstep : ℝ) := by
            nlinarith [hκ_le_one, hκ_nonneg, he0, hD_nonneg, hH_sum_le, hH1_nonneg, hH2_nonneg]

/-- **V2, dynamic all-time tracking with decaying floor**: if the
classic cascade holds at cycle 0 and the parameters satisfy the
dynamic closure (κ_j, χ_j eventually decreasing geometrically), the
sampled error obeys `e_j ≤ η` for all `j` AND the per-cycle DEFECT
`2κ_j(η + D) + 2χ_j D + ηstep_j`... here with FIXED ηstep the floor is
`ηstep`-limited; the leak-budget theorem (V4) consumes the κ/χ decay,
while tracking itself only needs the uniform `η` bound, as in P5. -/
theorem dyn_all_time_tracking
    {Conf : Type} [Primcodable Conf]
    (Mch : DiscreteMachine Conf) (d : ℕ) (E : LatticeEncoding Mch d)
    (S : RobustRealExtension Mch d E)
    (A : ℚ) (hA : 0 < A)
    (L : ℕ) (c₀ c₁ : ℚ) (hc₀ : 0 < c₀) (hc₁ : 0 < c₁)
    (hlam : 0 < (c₀ : ℝ) * (1/2)^L - (c₁ : ℝ)) (w : ℕ)
    (sol : DynIteratorSol d S.evalF A L c₀ c₁ (orbitPoint Mch E w 0))
    (D_K : ℝ) (hD : 0 < D_K)
    (hbox : ∀ (j : ℕ) (t : ℝ), t ∈ Set.Icc (2*π*j) (2*π*(j+1)) →
      (∀ i, |orbitPoint Mch E w (j+1) i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |sol.z t i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |sol.u t i - orbitPoint Mch E w j i| ≤ D_K) ∧
      (∀ i, |S.evalF (sol.u t) i - orbitPoint Mch E w j i| ≤ D_K))
    (η : ℝ) (hη : 0 < η)
    (hcasc : ∀ j : ℕ,
      2 * dynKappa (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * (η + D_K) + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K
        + (S.ηstep : ℝ) ≤ η ∧
      η + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K ≤ (S.r₀ : ℝ)) :
    ∀ j : ℕ, ∀ i,
      |sol.z (2*π*j) i - orbitPoint Mch E w j i| ≤ η ∧
      |sol.u (2*π*j) i - orbitPoint Mch E w j i| ≤ η := by
  intro j
  induction j with
  | zero =>
    intro i
    have h0 : 2*π*((0:ℕ):ℝ) = 0 := by norm_num
    rw [h0, sol.init_z, sol.init_u]
    constructor <;> · rw [sub_self, abs_zero]; exact hη.le
  | succ k ih =>
    intro i
    have hrec := dyn_perturbation_recurrence Mch d E S A hA L c₀ c₁ hc₀ hc₁
      hlam w sol D_K hD hbox k η hη.le ih (hcasc k).2
    obtain ⟨hz, hu⟩ := hrec i
    have hbound :
        2 * dynKappa (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) k * (η + D_K)
          + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) k * D_K
          + (S.ηstep : ℝ) ≤ η := (hcasc k).1
    have hcast : ((k+1:ℕ):ℝ) = (k:ℝ) + 1 := by push_cast; ring
    rw [hcast]
    exact ⟨le_trans hz hbound, le_trans hu hbound⟩

/-- **V3, dynamic parameter feasibility**: for every `η, D_K, r₀,
ηstep` (with `2 ηstep < η ≤ r₀/2`) there are `L M`-free rational
parameters `c₀ c₁ > 0` and `L : ℕ` such that the per-cycle cascade of
V2 holds for ALL `j` — the j = 0 case is the classic feasibility
(P6-style), and monotonicity in `j` (κ_j, χ_j decreasing under
`c₀ 2^{-L} > c₁ > c₀ 4^{-L}`) gives the rest. -/
theorem dyn_param_feasible
    (r₀ ηstep : ℚ) (h0 : 0 < ηstep) (h1 : ηstep < r₀)
    (D_K : ℝ) (hD : 0 < D_K) (η : ℝ)
    (hη₀ : 2 * (ηstep : ℝ) < η) (hη₁ : η ≤ (r₀ : ℝ) / 2) :
    ∃ (A : ℚ) (L : ℕ) (c₀ c₁ : ℚ), 0 < A ∧ 0 < c₀ ∧ 0 < c₁ ∧
      (c₀ : ℝ) * (1/2)^L > (c₁ : ℝ) ∧ (c₁ : ℝ) > (c₀ : ℝ) * (1/4)^L ∧
      ∀ j : ℕ,
        2 * dynKappa (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * (η + D_K) + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K
          + (ηstep : ℝ) ≤ η ∧
        η + 2 * dynChi (A : ℝ) L (c₀ : ℝ) (c₁ : ℝ) j * D_K ≤ (r₀ : ℝ) := by
  let e : ℝ := (ηstep : ℝ)
  let r : ℝ := (r₀ : ℝ)
  have he_pos : 0 < e := by
    change (0 : ℝ) < (ηstep : ℝ)
    exact_mod_cast h0
  have hr_pos : 0 < r := by
    change (0 : ℝ) < (r₀ : ℝ)
    exact_mod_cast (lt_trans h0 h1)
  have hη_pos : 0 < η := by nlinarith [he_pos, hη₀]
  have hm_pos : 0 < η - e := by nlinarith [he_pos, hη₀]
  have hrη_pos : 0 < r - η := by nlinarith [hr_pos, hη₁]
  let κstar : ℝ := min (1/4) ((η - e) / (8 * (D_K + η)))
  have hDη_pos : 0 < D_K + η := by nlinarith [hD, hη_pos]
  have hκstar_pos : 0 < κstar := by
    dsimp [κstar]
    exact lt_min (by norm_num) (div_pos hm_pos (by positivity))
  have hκstar_le_quarter : κstar ≤ (1/4 : ℝ) := by
    dsimp [κstar]
    exact min_le_left _ _
  have hκstar_le_margin : κstar ≤ (η - e) / (8 * (D_K + η)) := by
    dsimp [κstar]
    exact min_le_right _ _
  have hκstar_lt_one : κstar < 1 := by nlinarith [hκstar_le_quarter]
  have hinv_gt_one : 1 < 1 / κstar := by
    rw [one_lt_div₀ hκstar_pos]
    linarith
  let logMargin : ℝ := Real.log (1 / κstar)
  have hlog_pos : 0 < logMargin := by
    dsimp [logMargin]
    exact Real.log_pos hinv_gt_one
  let Bmin : ℝ := (2 * π / 3) * Real.exp (-1)
  have hBmin_pos : 0 < Bmin := by
    dsimp [Bmin]
    positivity
  let lowerA : ℝ := logMargin / Bmin
  have hlowerA_pos : 0 < lowerA := by
    dsimp [lowerA]
    positivity
  obtain ⟨Aq, hA_lower, hA_upper⟩ :=
    exists_rat_btwn (show lowerA < lowerA + 1 by linarith)
  have hAreal_pos : 0 < (Aq : ℝ) := lt_trans hlowerA_pos hA_lower
  have hAq_pos : 0 < Aq := Rat.cast_pos.mp hAreal_pos
  have hA_Bmin_ge_log : logMargin ≤ (Aq : ℝ) * Bmin := by
    have hmul := mul_lt_mul_of_pos_right hA_lower hBmin_pos
    dsimp [lowerA] at hmul
    have hBne : Bmin ≠ 0 := ne_of_gt hBmin_pos
    field_simp [hBne] at hmul
    simpa [mul_comm] using hmul.le
  let leakBudget : ℝ := min ((η - e) / 4) ((r - η) / 2)
  have hleakBudget_pos : 0 < leakBudget := by
    dsimp [leakBudget]
    exact lt_min (div_pos hm_pos (by norm_num)) (div_pos hrη_pos (by norm_num))
  have hleak_le_margin : leakBudget ≤ (η - e) / 4 := by
    dsimp [leakBudget]
    exact min_le_left _ _
  have hleak_le_final : leakBudget ≤ (r - η) / 2 := by
    dsimp [leakBudget]
    exact min_le_right _ _
  obtain ⟨Rq, hR_gt⟩ : ∃ q : ℚ, max 1 (((Aq : ℝ) * D_K) / leakBudget) < (q : ℝ) :=
    exists_rat_gt (max 1 (((Aq : ℝ) * D_K) / leakBudget))
  have hR_posR : 0 < (Rq : ℝ) := by
    have h1R : (1 : ℝ) ≤ max 1 (((Aq : ℝ) * D_K) / leakBudget) := le_max_left _ _
    nlinarith
  have hRq_pos : 0 < Rq := Rat.cast_pos.mp hR_posR
  have hAD_le_Rbudget : (Aq : ℝ) * D_K ≤ (Rq : ℝ) * leakBudget := by
    have hgt : ((Aq : ℝ) * D_K) / leakBudget < (Rq : ℝ) :=
      lt_of_le_of_lt (le_max_right _ _) hR_gt
    have hb := mul_lt_mul_of_pos_right hgt hleakBudget_pos
    field_simp [ne_of_gt hleakBudget_pos] at hb
    simpa [mul_comm] using hb.le
  obtain ⟨N, hNgt⟩ : ∃ N : ℕ, max 1 (8 * π * (Rq : ℝ)) < (N : ℝ) :=
    exists_nat_gt (max 1 (8 * π * (Rq : ℝ)))
  let L : ℕ := N
  let c0q : ℚ := 4 * Rq * (2 ^ L : ℚ)
  let c1q : ℚ := 2 * Rq * (1 + (1/2 : ℚ)^L)
  refine ⟨Aq, L, c0q, c1q, hAq_pos, ?_, ?_, ?_, ?_, ?_⟩
  · dsimp [c0q]
    positivity
  · dsimp [c1q]
    positivity
  · dsimp [c0q, c1q, L]
    have hLposR : (0 : ℝ) < (N : ℝ) := by
      have h1le : (1 : ℝ) ≤ max 1 (8 * π * (Rq : ℝ)) := le_max_left _ _
      nlinarith
    have hNpos : 0 < N := by exact_mod_cast hLposR
    have htwo_half : ((2 : ℝ)^N) * ((1/2 : ℝ)^N) = 1 := by
      rw [← mul_pow]
      norm_num
    have hhalf_lt : ((1/2 : ℝ)^N) < 1 := by
      apply pow_lt_one₀ (by norm_num) (by norm_num)
      exact ne_of_gt hNpos
    push_cast
    calc
      (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/2 : ℝ)^N
          = 4 * (Rq : ℝ) * (((2 : ℝ)^N) * (1/2 : ℝ)^N) := by ring
      _ = 4 * (Rq : ℝ) := by rw [htwo_half]; ring
      _ > 2 * (Rq : ℝ) * (1 + (1/2 : ℝ)^N) := by
        nlinarith [hR_posR, hhalf_lt]
  · dsimp [c0q, c1q, L]
    have hLposR : (0 : ℝ) < (N : ℝ) := by
      have h1le : (1 : ℝ) ≤ max 1 (8 * π * (Rq : ℝ)) := le_max_left _ _
      nlinarith
    have hNpos : 0 < N := by exact_mod_cast hLposR
    have htwo_four : ((2 : ℝ)^N) * ((1/4 : ℝ)^N) = (1/2 : ℝ)^N := by
      rw [← mul_pow]
      norm_num
    have hhalf_lt : ((1/2 : ℝ)^N) < 1 := by
      apply pow_lt_one₀ (by norm_num) (by norm_num)
      exact ne_of_gt hNpos
    push_cast
    calc
      (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/4 : ℝ)^N
          = 4 * (Rq : ℝ) * (((2 : ℝ)^N) * (1/4 : ℝ)^N) := by ring
      _ = 4 * (Rq : ℝ) * (1/2 : ℝ)^N := by rw [htwo_four]
      _ < 2 * (Rq : ℝ) * (1 + (1/2 : ℝ)^N) := by
        nlinarith [hR_posR, hhalf_lt]
  · intro j
    have hLposR : (0 : ℝ) < (N : ℝ) := by
      have h1le : (1 : ℝ) ≤ max 1 (8 * π * (Rq : ℝ)) := le_max_left _ _
      nlinarith
    have hN_ge_two : (2 : ℝ) ≤ (2 : ℝ)^N := by
      have hNpos : 0 < N := by exact_mod_cast hLposR
      cases N with
        | zero => cases hNpos
        | succ n =>
          have : (2 : ℝ) ^ (Nat.succ n) = 2 * (2 : ℝ)^n := by rw [pow_succ']
          rw [this]
          have hpow_ge_one : (1 : ℝ) ≤ (2 : ℝ)^n := one_le_pow₀ (by norm_num)
          nlinarith
    have hhalf_le_half : ((1/2 : ℝ)^N) ≤ 1/2 := by
      have hNpos : 0 < N := by exact_mod_cast hLposR
      cases N with
      | zero => cases hNpos
      | succ n =>
        rw [pow_succ']
        have : (1/2 : ℝ)^n ≤ 1 := pow_le_one₀ (by norm_num) (by norm_num)
        nlinarith
    have hpowN_gt_R : 8 * π * (Rq : ℝ) < (2 : ℝ)^N := by
      have hN_gt_R : 8 * π * (Rq : ℝ) < (N : ℝ) :=
        lt_of_le_of_lt (le_max_right _ _) hNgt
      have hN_lt_pow : (N : ℝ) < (2 : ℝ)^N := by
        exact_mod_cast (Nat.lt_two_pow_self : N < 2 ^ N)
      exact lt_trans hN_gt_R hN_lt_pow
    have hactive_small : 2 * π * (4 * (Rq : ℝ) / (2 : ℝ)^N) ≤ 1 := by
      have hpospow : 0 < (2 : ℝ)^N := pow_pos (by norm_num) N
      have hle : 8 * π * (Rq : ℝ) ≤ (2 : ℝ)^N := hpowN_gt_R.le
      calc
        2 * π * (4 * (Rq : ℝ) / (2 : ℝ)^N)
            = (8 * π * (Rq : ℝ)) / (2 : ℝ)^N := by ring
        _ ≤ 1 := by
          rw [div_le_one hpospow]
          exact hle
    have hLambda_ge_R :
        (Rq : ℝ) ≤ (c0q : ℝ) * (1/2)^L - (c1q : ℝ) := by
      dsimp [c0q, c1q, L]
      have htwo_half : ((2 : ℝ)^N) * ((1/2 : ℝ)^N) = 1 := by
        rw [← mul_pow]
        norm_num
      push_cast
      calc
        (Rq : ℝ) ≤ 2 * (Rq : ℝ) * (1 - (1/2 : ℝ)^N) := by
          nlinarith [hR_posR, hhalf_le_half]
        _ = (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/2 : ℝ)^N
              - 2 * (Rq : ℝ) * (1 + (1/2 : ℝ)^N) := by
          rw [show (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/2 : ℝ)^N
              = 4 * (Rq : ℝ) * (((2 : ℝ)^N) * (1/2 : ℝ)^N) by ring,
            htwo_half]
          ring
    have hchiD_le : dynChi (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * D_K ≤ leakBudget := by
      unfold dynChi
      have hLambda_pos : 0 < (c0q : ℝ) * (1/2)^L - (c1q : ℝ) :=
        lt_of_lt_of_le hR_posR hLambda_ge_R
      have hexp_le : Real.exp (-(((c0q : ℝ) * (1/2)^L - (c1q : ℝ)) * (2*π*j))) ≤ 1 := by
        rw [Real.exp_le_one_iff]
        have hπnn : 0 ≤ (2*π*(j:ℝ)) := by positivity
        nlinarith
      have hbase : (Aq : ℝ) * Real.exp (-(((c0q : ℝ) * (1/2)^L - (c1q : ℝ)) * (2*π*j)))
            / ((c0q : ℝ) * (1/2)^L - (c1q : ℝ)) ≤ (Aq : ℝ) / (Rq : ℝ) := by
          have hnum : (Aq : ℝ) * Real.exp (-(((c0q : ℝ) * (1/2)^L - (c1q : ℝ)) * (2*π*j))) ≤ (Aq : ℝ) := by
            nlinarith [mul_le_mul_of_nonneg_left hexp_le hAreal_pos.le]
          exact div_le_div₀ hAreal_pos.le hnum hR_posR hLambda_ge_R
      have hmul := mul_le_mul_of_nonneg_right hbase hD.le
      calc
        ((Aq : ℝ) * Real.exp (-(((c0q : ℝ) * (1/2)^L - (c1q : ℝ)) * (2*π*j)))
            / ((c0q : ℝ) * (1/2)^L - (c1q : ℝ))) * D_K
            ≤ ((Aq : ℝ) / (Rq : ℝ)) * D_K := hmul
        _ = ((Aq : ℝ) * D_K) / (Rq : ℝ) := by ring
        _ ≤ leakBudget := by
          rw [div_le_iff₀ hR_posR]
          simpa [mul_comm, mul_left_comm, mul_assoc] using hAD_le_Rbudget
    have hkappa_le : dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j ≤ κstar := by
      unfold dynKappa
      have hrate : (c0q : ℝ) * (1/4)^L < (c1q : ℝ) := by
        dsimp [c0q, c1q, L]
        have htwo_four : ((2 : ℝ)^N) * ((1/4 : ℝ)^N) = (1/2 : ℝ)^N := by
          rw [← mul_pow]
          norm_num
        have hhalf_pos : 0 < ((1/2 : ℝ)^N) := pow_pos (by norm_num) N
        push_cast
        calc
          (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/4 : ℝ)^N
              = 4 * (Rq : ℝ) * (1/2 : ℝ)^N := by
            rw [show (4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/4 : ℝ)^N
                = 4 * (Rq : ℝ) * (((2 : ℝ)^N) * (1/4 : ℝ)^N) by ring,
              htwo_four]
          _ < 2 * (Rq : ℝ) * (1 + (1/2 : ℝ)^N) := by
            nlinarith [hR_posR, hhalf_le_half, hhalf_pos]
      have hinner_ge :
          logMargin ≤ (Aq : ℝ) * Real.exp ((c1q : ℝ) * 2*π*j)
              * Real.exp (-((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) * (2*π/3) := by
        have hphase : Real.exp (-1) ≤
            Real.exp ((c1q : ℝ) * 2*π*j
              - ((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) := by
          apply Real.exp_le_exp.mpr
          have hnonnegj : 0 ≤ 2*π*(j:ℝ) := by positivity
          have hsmall : ((c0q : ℝ) * (1/4)^L) * (2*π) ≤ 1 := by
            dsimp [c0q, L]
            have hpow_pos : 0 < (2 : ℝ)^N := pow_pos (by norm_num) N
            have hpow_ne : ((2 : ℝ)^N) ≠ 0 := ne_of_gt hpow_pos
            have htwo_four : ((2 : ℝ)^N) * ((1/4 : ℝ)^N) = (1/2 : ℝ)^N := by
              rw [← mul_pow]
              norm_num
            have htwo_half : ((2 : ℝ)^N) * ((1/2 : ℝ)^N) = 1 := by
              rw [← mul_pow]
              norm_num
            have hhalf_eq : ((1/2 : ℝ)^N) = 1 / ((2 : ℝ)^N) := by
              rw [eq_div_iff hpow_ne]
              simpa [mul_comm] using htwo_half
            push_cast
            calc
              ((4 * (Rq : ℝ) * (2 : ℝ)^N) * (1/4 : ℝ)^N) * (2*π)
                  = 2*π * (4 * (Rq : ℝ) * (((2 : ℝ)^N) * (1/4 : ℝ)^N)) := by
                ring
              _ = 2*π * (4 * (Rq : ℝ) * (1/2 : ℝ)^N) := by rw [htwo_four]
              _ = 2*π * (4 * (Rq : ℝ) / (2 : ℝ)^N) := by rw [hhalf_eq]; ring
              _ ≤ 1 := hactive_small
          set q : ℝ := (c0q : ℝ) * (1/4)^L
          have hq_le_c1 : q ≤ (c1q : ℝ) := by
            dsimp [q]
            exact hrate.le
          have hmain : q * (2*π*(j:ℝ)) ≤ (c1q : ℝ) * (2*π*(j:ℝ)) :=
            mul_le_mul_of_nonneg_right hq_le_c1 hnonnegj
          have htail : q * (2*π) ≤ 1 := by
            dsimp [q] at hsmall ⊢
            simpa [mul_comm, mul_left_comm, mul_assoc] using hsmall
          have hdecomp :
              (c1q : ℝ) * 2*π*j - ((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)
                = ((c1q : ℝ) * (2*π*j) - q * (2*π*j)) - q * (2*π) := by
            dsimp [q]
            ring
          rw [hdecomp]
          nlinarith
        have hmul := mul_le_mul_of_nonneg_left hphase hAreal_pos.le
        have hmul2 := mul_le_mul_of_nonneg_right hmul (by positivity : 0 ≤ 2*π/3)
        calc
          logMargin ≤ (Aq : ℝ) * Bmin := hA_Bmin_ge_log
          _ = (Aq : ℝ) * Real.exp (-1) * (2*π/3) := by dsimp [Bmin]; ring
          _ ≤ (Aq : ℝ) * Real.exp ((c1q : ℝ) * 2*π*j
              - ((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) * (2*π/3) := hmul2
          _ = (Aq : ℝ) * Real.exp ((c1q : ℝ) * 2*π*j)
              * Real.exp (-((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) * (2*π/3) := by
                rw [show (c1q : ℝ) * 2*π*j
                    - ((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)
                    = (c1q : ℝ) * 2*π*j
                        + (-((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) by ring,
                  Real.exp_add]
                ring
      calc
        Real.exp (-((Aq : ℝ) * Real.exp ((c1q : ℝ) * 2*π*j)
            * Real.exp (-((c0q : ℝ) * 2*π*(j+1) * (1/4)^L)) * (2*π/3)))
            ≤ Real.exp (-logMargin) := by
              exact Real.exp_le_exp.mpr (neg_le_neg hinner_ge)
        _ = κstar := by
          dsimp [logMargin]
          rw [Real.exp_neg, Real.exp_log (by positivity : 0 < 1 / κstar)]
          field_simp [ne_of_gt hκstar_pos]
    constructor
    · have hκterm : 2 * dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * (D_K + η)
          ≤ (η - e) / 4 := by
        have hκ_le_margin := le_trans hkappa_le hκstar_le_margin
        have hmul := mul_le_mul_of_nonneg_right hκ_le_margin
          (show 0 ≤ 2 * (D_K + η) by positivity)
        have hden : 0 < 8 * (D_K + η) := by positivity
        calc
          2 * dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * (D_K + η)
              = dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * (2 * (D_K + η)) := by ring
          _ ≤ ((η - e) / (8 * (D_K + η))) * (2 * (D_K + η)) := hmul
          _ = (η - e) / 4 := by
            field_simp [ne_of_gt hDη_pos]
            ring
      have hχterm : 2 * (dynChi (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * D_K) ≤ (η - e) / 2 := by
        nlinarith [hchiD_le, hleak_le_margin]
      have hrewrite :
          2 * dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * (η + D_K)
            = 2 * dynKappa (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * (D_K + η) := by ring
      rw [hrewrite]
      nlinarith
    · change η + 2 * dynChi (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * D_K ≤ r
      have hχfinal : 2 * (dynChi (Aq : ℝ) L (c0q : ℝ) (c1q : ℝ) j * D_K) ≤ r - η := by
        nlinarith [hchiD_le, hleak_le_final]
      nlinarith

/-- χ-summability (replaces the DELETED V4: the depth-amplified
budget `Σ χ_{j'} k^{j−j'}` DIVERGES as stated — the `j' = 0` term
carries `k^j`; oracle finding 2026-06-11, notes/sec3-redesign — and
the per-digit bookkeeping lives in the §4 instance analysis, not at
tracking level).  What tracking needs is just geometric summability
of the leak constants. -/
theorem dynChi_summable (A : ℝ) (L : ℕ) (c₀ c₁ : ℝ)
    (hr : 0 < c₀ * (1/2)^L - c₁) :
    Summable (fun j : ℕ => dynChi A L c₀ c₁ j) := by
  have hgeom : Summable (fun j : ℕ =>
      (Real.exp (-((c₀ * (1/2)^L - c₁) * (2*π))))^j) := by
    apply summable_geometric_of_lt_one (Real.exp_pos _).le
    rw [Real.exp_lt_one_iff]
    have hπ := Real.pi_pos
    nlinarith
  have h2 : Summable (fun j : ℕ =>
      A * (Real.exp (-((c₀ * (1/2)^L - c₁) * (2*π))))^j
        / (c₀ * (1/2)^L - c₁)) :=
    (hgeom.mul_left A).div_const _
  have hfun : (fun j : ℕ => A * (Real.exp (-((c₀ * (1/2)^L - c₁) * (2*π))))^j
      / (c₀ * (1/2)^L - c₁))
      = (fun j : ℕ => dynChi A L c₀ c₁ j) := by
    funext j
    unfold dynChi
    rw [← Real.exp_nat_mul]
    congr 2
    push_cast
    ring
  rw [hfun] at h2
  exact h2

end Ripple.BoundedUniversality.BGP
