/-
  Ripple.Number.AttractorIntegralEquivalence — Exploratory scaffold.

  **Status: research stub, NOT a finished theorem.**

  ## Motivation

  In Ripple so far two "styles" of CRN-computable-number constructions have
  appeared:

  * **Integral / closed-trajectory class.** Examples: `π/4`, `log 2`, `1/e`,
    Catalan-like constants, `γ`. The author already possesses an explicit
    closed-form function `x : ℝ → ℝ` (built from `exp`, `arctan`, polynomial
    composition, division by strictly-positive denominators, …) and
    reverse-engineers a polynomial vector field whose unique solution matches
    that closed form. Convergence is read off the closed form directly
    (e.g. `arctan(1 - exp(-t)) → π/4`).

  * **ODE-attractor class.** Paradigmatic example: the Dottie number `d`,
    the unique fixed point of `x ↦ cos x`. Here `d` is *defined* as the
    limit of the trajectory of `x' = cos x − x` from `x(0) = 0`. No
    elementary closed form is known for `x(t)`. Existence of the trajectory
    comes from Picard–Lindelöf via a globally Lipschitz field; convergence
    comes from an invariant interval plus Grönwall-style exponential decay.

  Xiang's question: is this distinction *essential*, or is there an
  equivalence between the two classes inside Ripple?

  ## Verdict (first-pass, 2026-04-20): (a) — the distinction is
  metamathematical, not Lean-visible.

  At the level of `Ripple.BoundedTimeComputable`, both styles produce the
  exact same shape of witness:
  ```
  structure BoundedTimeComputable (d : ℕ) (α : ℝ) where
    pivp       : PIVP d
    sol        : PIVP.Solution pivp
    modulus    : TimeModulus
    bounded    : pivp.IsBounded sol.trajectory
    convergence: …
  ```
  The field `sol.trajectory : ℝ → Fin d → ℝ` is just a function. The type
  carries NO syntactic record of whether that function was constructed from
  Mathlib's `Real.exp`, `Real.arctan`, etc., or obtained abstractly via
  `ODE.PicardLindelof.existence`. Consequently, the propositions
  `IsIntegralClass α` and `IsAttractorClass α` — if defined as "∃ a BTC
  witness" modulo some putative syntactic predicate on the trajectory — both
  collapse to `IsCRNComputable α` as soon as that syntactic predicate is
  inhabited by the respective canonical witness.

  To make the question mathematically non-trivial one must *enrich* the
  definition. Two natural enrichments (both sketched below as `Prop`s we do
  NOT attempt to prove):

  1. **Liouvillian-trajectory class.** Require the trajectory to lie in a
     differential subfield of `C^∞(ℝ, ℝ)` generated by `ℚ(t)` under finite
     towers of (i) algebraic extensions, (ii) `exp`, (iii) `log`. This is
     the Liouville / Risch world. Proving a specific number (e.g. Dottie)
     is *not* in this class requires transcendence-theoretic tools (Kolchin
     / differential Galois), which are well beyond current Mathlib.

  2. **Elementary-definable-limit class.** Require existence of an
     elementary function `f : ℝ → ℝ` with `f t → α` and `f` is the
     trajectory of a polynomial ODE. Similar obstruction.

  Under either enrichment the two classes would likely be **distinct**
  (with Dottie as the conjectured separator), but proving separation is a
  research project in its own right. Under the *present* Ripple definitions,
  the classes coincide by construction.

  ## What this file does

  * States `IsIntegralClass` and `IsAttractorClass` as **proposed**
    definitions, clearly flagged as non-standard.
  * States the trivial equivalence at the bare BTC level
    (`equivalence_trivial`): both imply `IsCRNComputable`, and given any
    `IsCRNComputable` witness, the trajectory is both "the limit of the
    trajectory" (attractor side, tautologically) and — modulo the
    non-trivial Liouvillian refinement — putatively integral.
  * States the **non-trivial** separation conjecture as
    `conjecture_dottie_not_liouvillian` with a `sorry` placeholder.

  No `axiom`s. Every gap is `sorry` with a comment.
-/

import Ripple.Core.BoundedTime

namespace Ripple.Number.AttractorIntegralEquivalence

open Ripple

/-! ## Bare-BTC-level definitions (trivially equivalent) -/

/-- "Integral class": there exists a BTC witness whose trajectory is
(postulated to be) expressible in closed form. At the bare BTC level, the
predicate "closed form" is not representable, so we stub this to the
underlying `IsCRNComputable`. This is precisely the point: at Ripple's
current granularity, the predicate has no independent content. -/
def IsIntegralClass (α : ℝ) : Prop := IsCRNComputable α

/-- "Attractor class": there exists a BTC witness where `α` is the
`atTop` limit of the output coordinate (an attractor). Every BTC witness
already has this property via `BoundedTimeComputable.to_tendsto`, so — at
the bare BTC level — this collapses to `IsCRNComputable` as well. -/
def IsAttractorClass (α : ℝ) : Prop := IsCRNComputable α

/-- **Bare-BTC equivalence (trivial).** At the level of Ripple's current
`BoundedTimeComputable`, the two classes coincide because neither admits
syntactic distinction between "closed-form trajectory" and "abstract
attractor". Both are equal, by *definition* above, to `IsCRNComputable`. -/
theorem equivalence_trivial (α : ℝ) :
    IsIntegralClass α ↔ IsAttractorClass α := Iff.rfl

/-- Every BTC witness is an attractor witness: the output trajectory
converges to `α` by the convergence field of the structure, via the
existing `BoundedTimeComputable.to_tendsto` lemma. This is what makes
`IsAttractorClass = IsCRNComputable` sensible. -/
theorem crn_to_attractor {α : ℝ} (h : IsCRNComputable α) :
    ∃ d : ℕ, ∃ btc : BoundedTimeComputable d α,
      Filter.Tendsto (fun t => btc.sol.trajectory t btc.pivp.output)
        Filter.atTop (nhds α) := by
  obtain ⟨d, btc, _⟩ := h
  exact ⟨d, btc, btc.to_tendsto⟩

/-! ## Non-trivial refinement: Liouvillian trajectories

We sketch — but do not develop — a refined predicate that would make the
distinction mathematical rather than stylistic. The definitions below are
intentionally minimal: they merely NAME the missing concepts. -/

/-- A trajectory is "Liouvillian" if it lies in a differential subfield of
`C^∞(ℝ,ℝ)` generated by `ℚ(t)` under finite towers of algebraic extensions,
exponentials, and logarithms. **Formalizing this requires differential
algebra infrastructure that does not yet exist in Mathlib.** Stubbed as
`False` so that no vacuous theorem can be extracted; any downstream use
will immediately demand a proof. -/
def IsLiouvillianTrajectory (_traj : ℝ → ℝ) : Prop := False

/-- Refined "integral class": there is a BTC witness whose output
trajectory is Liouvillian. -/
def IsLiouvillianIntegralClass (α : ℝ) : Prop :=
  ∃ d : ℕ, ∃ btc : BoundedTimeComputable d α,
    IsLiouvillianTrajectory (fun t => btc.sol.trajectory t btc.pivp.output)

/-- Refined "attractor class": there is a BTC witness whose output
trajectory is NOT Liouvillian — i.e. genuinely defined as an ODE limit
with no elementary closed form. -/
def IsStrictAttractorClass (α : ℝ) : Prop :=
  ∃ d : ℕ, ∃ btc : BoundedTimeComputable d α,
    ¬ IsLiouvillianTrajectory (fun t => btc.sol.trajectory t btc.pivp.output)

/-- **Conjecture.** Under the refined predicates, the two classes are
distinct: the Dottie number admits an attractor-class witness but no
Liouvillian witness. Proving the negative half is a transcendence problem
requiring differential Galois / Kolchin theory, well beyond Mathlib's
current reach. -/
theorem conjecture_refined_classes_separate :
    ∃ α : ℝ,
      IsStrictAttractorClass α ∧ ¬ IsLiouvillianIntegralClass α := by
  -- Proof outline (NOT Lean-executable at Mathlib's current state):
  --   · Take α = dottieNumber (Ripple.Number.Dottie).
  --   · Attractor witness: `dottie_is_realtime` constructs a BTC whose
  --     trajectory is the Picard–Lindelöf solution of `x' = cos x − x`.
  --     Its output coordinate is `x(t)` itself, which is not Liouvillian:
  --     by Kolchin's theorem, if `x(t)` were Liouvillian then `cos x(t)`
  --     would be in a Liouvillian extension, forcing the equation
  --     `x' = cos x − x` to have a Liouvillian solution; but
  --     `cos x − x = 0` has only the trivial algebraic fixed-point
  --     structure, and the non-constant orbit is provably transcendental
  --     over `ℚ(t, exp, log)`.
  --   · Non-Liouvillian half: any BTC witness for `dottieNumber` produces
  --     a trajectory whose output coordinate tends to `dottieNumber`. A
  --     finite-dimensional polynomial ODE with rational initial conditions
  --     whose output coordinate is Liouvillian and tends to `dottieNumber`
  --     would contradict the transcendence of `dottieNumber` over the
  --     Liouvillian numbers (conjecturally; weaker than Schanuel).
  -- None of the above is in Mathlib. Leaving as `sorry`.
  sorry

/-! ## The *real* open question this exploration surfaces

Is the class of CRN-computable reals strictly larger than the class of
"numbers expressible as `lim_{t→∞} f(t)` for some Liouvillian `f` that is
itself the output of a polynomial ODE"?

Conjecturally **yes**, with the Dottie number as a witness. Proving it
requires differential Galois machinery not present in Mathlib, so for the
immediate formalization project the distinction remains stylistic.
The engineering takeaway for Ripple: do NOT try to separate "integral"
and "attractor" witnesses at the type level — keep them both as plain
`BoundedTimeComputable`, and treat the stylistic split as a convention of
the proof files that produce them. -/

end Ripple.Number.AttractorIntegralEquivalence
